// AUTO-GENERATED by webapp/build_member_bills.py (Congress.gov). No API key stored here.
window.MEMBER_BILLS = {
 "source": "Congress.gov API",
 "byBioguide": {
  "F000110": {
   "sponsored": 27,
   "cosponsored": 588,
   "total": 615
  },
  "S000168": {
   "sponsored": 73,
   "cosponsored": 1309,
   "total": 1382
  },
  "M001136": {
   "sponsored": 70,
   "cosponsored": 486,
   "total": 556
  },
  "L000590": {
   "sponsored": 98,
   "cosponsored": 1259,
   "total": 1357
  },
  "G000596": {
   "sponsored": 111,
   "cosponsored": 432,
   "total": 543
  },
  "M001217": {
   "sponsored": 38,
   "cosponsored": 787,
   "total": 825
  },
  "G000583": {
   "sponsored": 204,
   "cosponsored": 3233,
   "total": 3437
  },
  "D000032": {
   "sponsored": 146,
   "cosponsored": 1305,
   "total": 1451
  },
  "M001234": {
   "sponsored": 15,
   "cosponsored": 224,
   "total": 239
  },
  "N000189": {
   "sponsored": 168,
   "cosponsored": 1563,
   "total": 1731
  },
  "B001327": {
   "sponsored": 20,
   "cosponsored": 289,
   "total": 309
  },
  "R000614": {
   "sponsored": 230,
   "cosponsored": 669,
   "total": 899
  },
  "M001218": {
   "sponsored": 54,
   "cosponsored": 525,
   "total": 579
  },
  "L000566": {
   "sponsored": 239,
   "cosponsored": 2320,
   "total": 2559
  },
  "C001123": {
   "sponsored": 32,
   "cosponsored": 1149,
   "total": 1181
  },
  "D000399": {
   "sponsored": 263,
   "cosponsored": 3783,
   "total": 4046
  },
  "W000797": {
   "sponsored": 176,
   "cosponsored": 4431,
   "total": 4607
  },
  "B001291": {
   "sponsored": 103,
   "cosponsored": 2200,
   "total": 2303
  },
  "A000372": {
   "sponsored": 71,
   "cosponsored": 1372,
   "total": 1443
  },
  "S001214": {
   "sponsored": 275,
   "cosponsored": 1644,
   "total": 1919
  },
  "C001055": {
   "sponsored": 135,
   "cosponsored": 3084,
   "total": 3219
  },
  "F000450": {
   "sponsored": 262,
   "cosponsored": 1753,
   "total": 2015
  },
  "C001101": {
   "sponsored": 88,
   "cosponsored": 1850,
   "total": 1938
  },
  "W000798": {
   "sponsored": 222,
   "cosponsored": 2113,
   "total": 2335
  },
  "F000483": {
   "sponsored": 10,
   "cosponsored": 302,
   "total": 312
  },
  "P000048": {
   "sponsored": 158,
   "cosponsored": 871,
   "total": 1029
  },
  "D000624": {
   "sponsored": 269,
   "cosponsored": 3062,
   "total": 3331
  },
  "D000626": {
   "sponsored": 154,
   "cosponsored": 856,
   "total": 1010
  },
  "S001212": {
   "sponsored": 98,
   "cosponsored": 1269,
   "total": 1367
  },
  "L000597": {
   "sponsored": 44,
   "cosponsored": 358,
   "total": 402
  },
  "S001185": {
   "sponsored": 123,
   "cosponsored": 3187,
   "total": 3310
  },
  "K000376": {
   "sponsored": 183,
   "cosponsored": 2358,
   "total": 2541
  },
  "J000289": {
   "sponsored": 55,
   "cosponsored": 1322,
   "total": 1377
  },
  "N000147": {
   "sponsored": 1129,
   "cosponsored": 17332,
   "total": 18461
  },
  "G000591": {
   "sponsored": 54,
   "cosponsored": 1132,
   "total": 1186
  },
  "G000597": {
   "sponsored": 95,
   "cosponsored": 1056,
   "total": 1151
  },
  "A000379": {
   "sponsored": 51,
   "cosponsored": 359,
   "total": 410
  },
  "R000603": {
   "sponsored": 102,
   "cosponsored": 1670,
   "total": 1772
  },
  "M001227": {
   "sponsored": 49,
   "cosponsored": 874,
   "total": 923
  },
  "M001245": {
   "sponsored": 4,
   "cosponsored": 66,
   "total": 70
  },
  "S001211": {
   "sponsored": 79,
   "cosponsored": 1138,
   "total": 1217
  },
  "L000560": {
   "sponsored": 178,
   "cosponsored": 3644,
   "total": 3822
  },
  "M001204": {
   "sponsored": 68,
   "cosponsored": 1238,
   "total": 1306
  },
  "A000055": {
   "sponsored": 104,
   "cosponsored": 2294,
   "total": 2398
  },
  "M001239": {
   "sponsored": 19,
   "cosponsored": 284,
   "total": 303
  },
  "S001156": {
   "sponsored": 250,
   "cosponsored": 4854,
   "total": 5104
  },
  "D000616": {
   "sponsored": 52,
   "cosponsored": 1512,
   "total": 1564
  },
  "K000398": {
   "sponsored": 54,
   "cosponsored": 672,
   "total": 726
  },
  "B000668": {
   "sponsored": 28,
   "cosponsored": 353,
   "total": 381
  },
  "J000309": {
   "sponsored": 14,
   "cosponsored": 1031,
   "total": 1045
  },
  "S000510": {
   "sponsored": 232,
   "cosponsored": 5003,
   "total": 5235
  },
  "S000250": {
   "sponsored": 456,
   "cosponsored": 4646,
   "total": 5102
  },
  "F000468": {
   "sponsored": 58,
   "cosponsored": 1210,
   "total": 1268
  },
  "W000816": {
   "sponsored": 140,
   "cosponsored": 1381,
   "total": 1521
  },
  "G000603": {
   "sponsored": 21,
   "cosponsored": 313,
   "total": 334
  },
  "C001108": {
   "sponsored": 50,
   "cosponsored": 611,
   "total": 661
  },
  "B001325": {
   "sponsored": 13,
   "cosponsored": 259,
   "total": 272
  },
  "S001201": {
   "sponsored": 84,
   "cosponsored": 2782,
   "total": 2866
  },
  "F000472": {
   "sponsored": 47,
   "cosponsored": 796,
   "total": 843
  },
  "S001199": {
   "sponsored": 109,
   "cosponsored": 952,
   "total": 1061
  },
  "S001189": {
   "sponsored": 86,
   "cosponsored": 1630,
   "total": 1716
  },
  "C001068": {
   "sponsored": 490,
   "cosponsored": 8464,
   "total": 8954
  },
  "M001236": {
   "sponsored": 26,
   "cosponsored": 260,
   "total": 286
  },
  "L000595": {
   "sponsored": 32,
   "cosponsored": 447,
   "total": 479
  },
  "E000296": {
   "sponsored": 63,
   "cosponsored": 3078,
   "total": 3141
  },
  "T000486": {
   "sponsored": 167,
   "cosponsored": 1283,
   "total": 1450
  },
  "A000148": {
   "sponsored": 23,
   "cosponsored": 974,
   "total": 997
  },
  "M001232": {
   "sponsored": 29,
   "cosponsored": 412,
   "total": 441
  },
  "J000305": {
   "sponsored": 79,
   "cosponsored": 1360,
   "total": 1439
  },
  "T000490": {
   "sponsored": 33,
   "cosponsored": 176,
   "total": 209
  },
  "H001094": {
   "sponsored": 24,
   "cosponsored": 612,
   "total": 636
  },
  "H001072": {
   "sponsored": 148,
   "cosponsored": 1137,
   "total": 1285
  },
  "J000310": {
   "sponsored": 25,
   "cosponsored": 419,
   "total": 444
  },
  "H001082": {
   "sponsored": 70,
   "cosponsored": 724,
   "total": 794
  },
  "P000197": {
   "sponsored": 199,
   "cosponsored": 5080,
   "total": 5279
  },
  "R000612": {
   "sponsored": 44,
   "cosponsored": 753,
   "total": 797
  }
 },
 "count": 76
};
