// AUTO-GENERATED by webapp/build_member_bills.py (Congress.gov). No API key stored here.
window.MEMBER_BILLS = {
 "source": "Congress.gov API",
 "byBioguide": {
  "F000110": {
   "sponsored": 27,
   "cosponsored": 589,
   "total": 616
  },
  "S000168": {
   "sponsored": 73,
   "cosponsored": 1318,
   "total": 1391
  },
  "M001136": {
   "sponsored": 70,
   "cosponsored": 486,
   "total": 556
  },
  "L000590": {
   "sponsored": 98,
   "cosponsored": 1260,
   "total": 1358
  },
  "G000596": {
   "sponsored": 111,
   "cosponsored": 432,
   "total": 543
  },
  "M001217": {
   "sponsored": 38,
   "cosponsored": 792,
   "total": 830
  },
  "G000583": {
   "sponsored": 205,
   "cosponsored": 3238,
   "total": 3443
  },
  "D000032": {
   "sponsored": 146,
   "cosponsored": 1305,
   "total": 1451
  },
  "M001234": {
   "sponsored": 16,
   "cosponsored": 229,
   "total": 245
  },
  "N000189": {
   "sponsored": 168,
   "cosponsored": 1565,
   "total": 1733
  },
  "B001327": {
   "sponsored": 20,
   "cosponsored": 293,
   "total": 313
  },
  "R000614": {
   "sponsored": 230,
   "cosponsored": 670,
   "total": 900
  },
  "M001218": {
   "sponsored": 54,
   "cosponsored": 528,
   "total": 582
  },
  "L000566": {
   "sponsored": 239,
   "cosponsored": 2322,
   "total": 2561
  },
  "C001123": {
   "sponsored": 32,
   "cosponsored": 1164,
   "total": 1196
  },
  "D000399": {
   "sponsored": 263,
   "cosponsored": 3787,
   "total": 4050
  },
  "W000797": {
   "sponsored": 176,
   "cosponsored": 4447,
   "total": 4623
  },
  "B001291": {
   "sponsored": 104,
   "cosponsored": 2205,
   "total": 2309
  },
  "A000372": {
   "sponsored": 71,
   "cosponsored": 1379,
   "total": 1450
  },
  "S001214": {
   "sponsored": 276,
   "cosponsored": 1648,
   "total": 1924
  },
  "C001055": {
   "sponsored": 135,
   "cosponsored": 3093,
   "total": 3228
  },
  "F000450": {
   "sponsored": 262,
   "cosponsored": 1755,
   "total": 2017
  },
  "C001101": {
   "sponsored": 88,
   "cosponsored": 1850,
   "total": 1938
  },
  "W000798": {
   "sponsored": 223,
   "cosponsored": 2115,
   "total": 2338
  },
  "F000483": {
   "sponsored": 11,
   "cosponsored": 307,
   "total": 318
  },
  "P000048": {
   "sponsored": 159,
   "cosponsored": 874,
   "total": 1033
  },
  "D000624": {
   "sponsored": 270,
   "cosponsored": 3069,
   "total": 3339
  },
  "D000626": {
   "sponsored": 154,
   "cosponsored": 859,
   "total": 1013
  },
  "S001212": {
   "sponsored": 98,
   "cosponsored": 1274,
   "total": 1372
  },
  "L000597": {
   "sponsored": 44,
   "cosponsored": 361,
   "total": 405
  },
  "S001185": {
   "sponsored": 123,
   "cosponsored": 3194,
   "total": 3317
  },
  "K000376": {
   "sponsored": 184,
   "cosponsored": 2363,
   "total": 2547
  },
  "J000289": {
   "sponsored": 55,
   "cosponsored": 1322,
   "total": 1377
  },
  "N000147": {
   "sponsored": 1131,
   "cosponsored": 17376,
   "total": 18507
  },
  "C001080": {
   "sponsored": 254,
   "cosponsored": 5323,
   "total": 5577
  },
  "G000591": {
   "sponsored": 54,
   "cosponsored": 1133,
   "total": 1187
  },
  "G000597": {
   "sponsored": 96,
   "cosponsored": 1057,
   "total": 1153
  },
  "A000379": {
   "sponsored": 51,
   "cosponsored": 366,
   "total": 417
  },
  "R000603": {
   "sponsored": 102,
   "cosponsored": 1671,
   "total": 1773
  },
  "M001227": {
   "sponsored": 49,
   "cosponsored": 889,
   "total": 938
  },
  "M001245": {
   "sponsored": 4,
   "cosponsored": 71,
   "total": 75
  },
  "S001211": {
   "sponsored": 79,
   "cosponsored": 1140,
   "total": 1219
  },
  "L000560": {
   "sponsored": 179,
   "cosponsored": 3645,
   "total": 3824
  },
  "M001204": {
   "sponsored": 68,
   "cosponsored": 1239,
   "total": 1307
  },
  "A000055": {
   "sponsored": 104,
   "cosponsored": 2296,
   "total": 2400
  },
  "M001239": {
   "sponsored": 19,
   "cosponsored": 286,
   "total": 305
  },
  "S001156": {
   "sponsored": 250,
   "cosponsored": 4858,
   "total": 5108
  },
  "D000616": {
   "sponsored": 52,
   "cosponsored": 1513,
   "total": 1565
  },
  "K000398": {
   "sponsored": 54,
   "cosponsored": 678,
   "total": 732
  },
  "B000668": {
   "sponsored": 29,
   "cosponsored": 354,
   "total": 383
  },
  "J000309": {
   "sponsored": 14,
   "cosponsored": 1045,
   "total": 1059
  },
  "S000510": {
   "sponsored": 232,
   "cosponsored": 5010,
   "total": 5242
  },
  "S000250": {
   "sponsored": 456,
   "cosponsored": 4650,
   "total": 5106
  },
  "F000468": {
   "sponsored": 58,
   "cosponsored": 1213,
   "total": 1271
  },
  "W000816": {
   "sponsored": 140,
   "cosponsored": 1381,
   "total": 1521
  },
  "G000603": {
   "sponsored": 21,
   "cosponsored": 315,
   "total": 336
  },
  "C001108": {
   "sponsored": 50,
   "cosponsored": 612,
   "total": 662
  },
  "B001325": {
   "sponsored": 15,
   "cosponsored": 263,
   "total": 278
  },
  "S001201": {
   "sponsored": 85,
   "cosponsored": 2789,
   "total": 2874
  },
  "F000472": {
   "sponsored": 47,
   "cosponsored": 798,
   "total": 845
  },
  "S001199": {
   "sponsored": 109,
   "cosponsored": 954,
   "total": 1063
  },
  "C001068": {
   "sponsored": 491,
   "cosponsored": 8481,
   "total": 8972
  },
  "M001236": {
   "sponsored": 26,
   "cosponsored": 264,
   "total": 290
  },
  "L000595": {
   "sponsored": 32,
   "cosponsored": 448,
   "total": 480
  },
  "E000296": {
   "sponsored": 63,
   "cosponsored": 3086,
   "total": 3149
  },
  "T000486": {
   "sponsored": 167,
   "cosponsored": 1290,
   "total": 1457
  },
  "A000148": {
   "sponsored": 23,
   "cosponsored": 977,
   "total": 1000
  },
  "M001232": {
   "sponsored": 29,
   "cosponsored": 415,
   "total": 444
  },
  "J000305": {
   "sponsored": 80,
   "cosponsored": 1366,
   "total": 1446
  },
  "T000490": {
   "sponsored": 33,
   "cosponsored": 177,
   "total": 210
  },
  "H001094": {
   "sponsored": 24,
   "cosponsored": 618,
   "total": 642
  },
  "H001072": {
   "sponsored": 148,
   "cosponsored": 1137,
   "total": 1285
  },
  "J000310": {
   "sponsored": 25,
   "cosponsored": 426,
   "total": 451
  },
  "H001082": {
   "sponsored": 71,
   "cosponsored": 725,
   "total": 796
  },
  "P000197": {
   "sponsored": 199,
   "cosponsored": 5083,
   "total": 5282
  },
  "R000612": {
   "sponsored": 44,
   "cosponsored": 762,
   "total": 806
  }
 },
 "count": 76
};
