// AUTO-GENERATED by webapp/build_usaspending.py (USASpending.gov)
window.USA_DATA = {
 "source": "USASpending.gov (federal awards 2020-2025)",
 "byTicker": {
  "XOM": {
   "recipient": "ExxonMobil",
   "total_contracts": 81419306.68,
   "total_contracts_fmt": "$81.4M",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 81419306.68,
     "amount_fmt": "$81.4M"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=ExxonMobil"
  },
  "CVX": {
   "recipient": "Chevron",
   "total_contracts": 964668177.13,
   "total_contracts_fmt": "$964.7M",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 964237999.55,
     "amount_fmt": "$964.2M"
    },
    {
     "agency": "General Services Administration",
     "amount": 276767.82,
     "amount_fmt": "$277K"
    },
    {
     "agency": "Department of State",
     "amount": 143409.76,
     "amount_fmt": "$143K"
    },
    {
     "agency": "Department of the Interior",
     "amount": 10000.0,
     "amount_fmt": "$10K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Chevron"
  },
  "GM": {
   "recipient": "General Motors Company",
   "total_contracts": 2315410896.0499997,
   "total_contracts_fmt": "$2.3B",
   "top_agencies": [
    {
     "agency": "General Services Administration",
     "amount": 1563662270.56,
     "amount_fmt": "$1.6B"
    },
    {
     "agency": "Department of Health and Human Services",
     "amount": 476475711.19,
     "amount_fmt": "$476.5M"
    },
    {
     "agency": "Department of Defense",
     "amount": 165399809.77,
     "amount_fmt": "$165.4M"
    },
    {
     "agency": "Department of State",
     "amount": 63124830.08,
     "amount_fmt": "$63.1M"
    },
    {
     "agency": "Department of Homeland Security",
     "amount": 43317770.46,
     "amount_fmt": "$43.3M"
    },
    {
     "agency": "Pension Benefit Guaranty Corporation",
     "amount": 3430503.99,
     "amount_fmt": "$3.4M"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=General%20Motors%20Company"
  },
  "GE": {
   "recipient": "General Electric Company",
   "total_contracts": 21084401554.109993,
   "total_contracts_fmt": "$21.1B",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 19281961879.53,
     "amount_fmt": "$19.3B"
    },
    {
     "agency": "Department of Veterans Affairs",
     "amount": 770362217.69,
     "amount_fmt": "$770.4M"
    },
    {
     "agency": "Department of Health and Human Services",
     "amount": 423114561.19,
     "amount_fmt": "$423.1M"
    },
    {
     "agency": "National Aeronautics and Space Administration",
     "amount": 310631344.03,
     "amount_fmt": "$310.6M"
    },
    {
     "agency": "Department of Homeland Security",
     "amount": 260631854.05,
     "amount_fmt": "$260.6M"
    },
    {
     "agency": "Department of the Interior",
     "amount": 37699697.62,
     "amount_fmt": "$37.7M"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=General%20Electric%20Company"
  },
  "F": {
   "recipient": "Ford Motor Company",
   "total_contracts": 1622499453.0400002,
   "total_contracts_fmt": "$1.6B",
   "top_agencies": [
    {
     "agency": "General Services Administration",
     "amount": 1621473761.14,
     "amount_fmt": "$1.6B"
    },
    {
     "agency": "Department of Health and Human Services",
     "amount": 858980.57,
     "amount_fmt": "$859K"
    },
    {
     "agency": "Department of Homeland Security",
     "amount": 90975.0,
     "amount_fmt": "$91K"
    },
    {
     "agency": "Department of Defense",
     "amount": 48222.0,
     "amount_fmt": "$48K"
    },
    {
     "agency": "Department of the Interior",
     "amount": 35612.92,
     "amount_fmt": "$36K"
    },
    {
     "agency": "Agency for International Development",
     "amount": -8098.59,
     "amount_fmt": "$8K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Ford%20Motor%20Company"
  },
  "BAC": {
   "recipient": "Bank of America Corporation",
   "total_contracts": 17572319.88,
   "total_contracts_fmt": "$17.6M",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 17572789.88,
     "amount_fmt": "$17.6M"
    },
    {
     "agency": "Department of Justice",
     "amount": -470.0,
     "amount_fmt": "$470"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Bank%20of%20America%20Corporation"
  },
  "T": {
   "recipient": "AT&T",
   "total_contracts": 6101198428.860001,
   "total_contracts_fmt": "$6.1B",
   "top_agencies": [
    {
     "agency": "Department of Veterans Affairs",
     "amount": 2096457076.77,
     "amount_fmt": "$2.1B"
    },
    {
     "agency": "Department of Defense",
     "amount": 1337171783.81,
     "amount_fmt": "$1.3B"
    },
    {
     "agency": "Department of Justice",
     "amount": 752420301.67,
     "amount_fmt": "$752.4M"
    },
    {
     "agency": "Department of Homeland Security",
     "amount": 664774205.43,
     "amount_fmt": "$664.8M"
    },
    {
     "agency": "Department of State",
     "amount": 639225055.71,
     "amount_fmt": "$639.2M"
    },
    {
     "agency": "Department of the Treasury",
     "amount": 611150005.47,
     "amount_fmt": "$611.2M"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=AT%26T"
  },
  "BRK.B": {
   "recipient": "Berkshire Hathaway",
   "total_contracts": 1216828681.0399997,
   "total_contracts_fmt": "$1.2B",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 684946159.91,
     "amount_fmt": "$684.9M"
    },
    {
     "agency": "Department of the Treasury",
     "amount": 453309632.67,
     "amount_fmt": "$453.3M"
    },
    {
     "agency": "Department of Homeland Security",
     "amount": 51761594.24,
     "amount_fmt": "$51.8M"
    },
    {
     "agency": "Department of Transportation",
     "amount": 14271312.02,
     "amount_fmt": "$14.3M"
    },
    {
     "agency": "Department of Justice",
     "amount": 6848303.33,
     "amount_fmt": "$6.8M"
    },
    {
     "agency": "Department of Health and Human Services",
     "amount": 5691678.87,
     "amount_fmt": "$5.7M"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Berkshire%20Hathaway"
  },
  "JPM": {
   "recipient": "JPMorgan Chase & Co.",
   "total_contracts": 4552687.600000001,
   "total_contracts_fmt": "$4.6M",
   "top_agencies": [
    {
     "agency": "Pension Benefit Guaranty Corporation",
     "amount": 4055604.67,
     "amount_fmt": "$4.1M"
    },
    {
     "agency": "Department of Defense",
     "amount": 253352.37,
     "amount_fmt": "$253K"
    },
    {
     "agency": "Department of Homeland Security",
     "amount": 128275.75,
     "amount_fmt": "$128K"
    },
    {
     "agency": "Department of Health and Human Services",
     "amount": 104542.91,
     "amount_fmt": "$105K"
    },
    {
     "agency": "Department of Justice",
     "amount": 10911.9,
     "amount_fmt": "$11K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=JPMorgan%20Chase%20%26%20Co."
  },
  "IBM": {
   "recipient": "IBM",
   "total_contracts": 0,
   "total_contracts_fmt": null,
   "top_agencies": [],
   "url": "https://www.usaspending.gov/search?keyword=IBM"
  },
  "VZ": {
   "recipient": "Verizon Communications",
   "total_contracts": 2569633963.45,
   "total_contracts_fmt": "$2.6B",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 1382610453.41,
     "amount_fmt": "$1.4B"
    },
    {
     "agency": "Social Security Administration",
     "amount": 472659269.01,
     "amount_fmt": "$472.7M"
    },
    {
     "agency": "Department of Health and Human Services",
     "amount": 308879089.96,
     "amount_fmt": "$308.9M"
    },
    {
     "agency": "Department of the Treasury",
     "amount": 180453773.63,
     "amount_fmt": "$180.5M"
    },
    {
     "agency": "Department of Justice",
     "amount": 132121674.7,
     "amount_fmt": "$132.1M"
    },
    {
     "agency": "Department of Transportation",
     "amount": 92909702.74,
     "amount_fmt": "$92.9M"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Verizon%20Communications"
  },
  "GS": {
   "recipient": "Goldman Sachs",
   "total_contracts": 21021285.55,
   "total_contracts_fmt": "$21.0M",
   "top_agencies": [
    {
     "agency": "Pension Benefit Guaranty Corporation",
     "amount": 21021285.55,
     "amount_fmt": "$21.0M"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Goldman%20Sachs"
  },
  "HD": {
   "recipient": "Home Depot",
   "total_contracts": 434306.8,
   "total_contracts_fmt": "$434K",
   "top_agencies": [
    {
     "agency": "Department of Homeland Security",
     "amount": 215345.3,
     "amount_fmt": "$215K"
    },
    {
     "agency": "Department of Defense",
     "amount": 161464.5,
     "amount_fmt": "$161K"
    },
    {
     "agency": "Department of State",
     "amount": 28043.88,
     "amount_fmt": "$28K"
    },
    {
     "agency": "General Services Administration",
     "amount": 22299.6,
     "amount_fmt": "$22K"
    },
    {
     "agency": "Department of Justice",
     "amount": 15459.24,
     "amount_fmt": "$15K"
    },
    {
     "agency": "Department of Health and Human Services",
     "amount": -8305.72,
     "amount_fmt": "$8K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Home%20Depot"
  },
  "PG": {
   "recipient": "The Procter & Gamble Company",
   "total_contracts": 0,
   "total_contracts_fmt": null,
   "top_agencies": [],
   "url": "https://www.usaspending.gov/search?keyword=The%20Procter%20%26%20Gamble%20Company"
  },
  "UNH": {
   "recipient": "UnitedHealth Group",
   "total_contracts": 60024753107.009995,
   "total_contracts_fmt": "$60.0B",
   "top_agencies": [
    {
     "agency": "Department of Veterans Affairs",
     "amount": 58341475599.08,
     "amount_fmt": "$58.3B"
    },
    {
     "agency": "Department of Health and Human Services",
     "amount": 867292923.27,
     "amount_fmt": "$867.3M"
    },
    {
     "agency": "Department of Defense",
     "amount": 722062177.39,
     "amount_fmt": "$722.1M"
    },
    {
     "agency": "Department of Education",
     "amount": 60804299.67,
     "amount_fmt": "$60.8M"
    },
    {
     "agency": "Department of Homeland Security",
     "amount": 26708748.93,
     "amount_fmt": "$26.7M"
    },
    {
     "agency": "Department of the Interior",
     "amount": 6409358.67,
     "amount_fmt": "$6.4M"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=UnitedHealth%20Group"
  },
  "BA": {
   "recipient": "Boeing Company",
   "total_contracts": 139808235470.33002,
   "total_contracts_fmt": "$139.8B",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 130123451144.36,
     "amount_fmt": "$130.1B"
    },
    {
     "agency": "National Aeronautics and Space Administration",
     "amount": 9545909385.16,
     "amount_fmt": "$9.5B"
    },
    {
     "agency": "Department of Homeland Security",
     "amount": 79075332.82,
     "amount_fmt": "$79.1M"
    },
    {
     "agency": "General Services Administration",
     "amount": 39970957.73,
     "amount_fmt": "$40.0M"
    },
    {
     "agency": "Department of Justice",
     "amount": 11667055.54,
     "amount_fmt": "$11.7M"
    },
    {
     "agency": "Department of Transportation",
     "amount": 8161594.72,
     "amount_fmt": "$8.2M"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Boeing%20Company"
  },
  "TGT": {
   "recipient": "Target Corporation",
   "total_contracts": 0,
   "total_contracts_fmt": null,
   "top_agencies": [],
   "url": "https://www.usaspending.gov/search?keyword=Target%20Corporation"
  },
  "DELL": {
   "recipient": "Dell Inc",
   "total_contracts": 1635493.43,
   "total_contracts_fmt": "$1.6M",
   "top_agencies": [
    {
     "agency": "Department of Agriculture",
     "amount": 822219.0,
     "amount_fmt": "$822K"
    },
    {
     "agency": "Department of Defense",
     "amount": 468741.71,
     "amount_fmt": "$469K"
    },
    {
     "agency": "Department of Veterans Affairs",
     "amount": 344532.72,
     "amount_fmt": "$345K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Dell%20Inc"
  },
  "JNJ": {
   "recipient": "Johnson & Johnson",
   "total_contracts": 606614924.15,
   "total_contracts_fmt": "$606.6M",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 401975911.59,
     "amount_fmt": "$402.0M"
    },
    {
     "agency": "Department of Veterans Affairs",
     "amount": 131010705.34,
     "amount_fmt": "$131.0M"
    },
    {
     "agency": "Department of Health and Human Services",
     "amount": 69725824.2,
     "amount_fmt": "$69.7M"
    },
    {
     "agency": "Department of Justice",
     "amount": 2210927.34,
     "amount_fmt": "$2.2M"
    },
    {
     "agency": "General Services Administration",
     "amount": 1423147.68,
     "amount_fmt": "$1.4M"
    },
    {
     "agency": "Department of Agriculture",
     "amount": 268408.0,
     "amount_fmt": "$268K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Johnson%20%26%20Johnson"
  },
  "RTX": {
   "recipient": "RTX",
   "total_contracts": 107409026487.20001,
   "total_contracts_fmt": "$107.4B",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 104697497099.66,
     "amount_fmt": "$104.7B"
    },
    {
     "agency": "National Aeronautics and Space Administration",
     "amount": 870512211.25,
     "amount_fmt": "$870.5M"
    },
    {
     "agency": "Department of Transportation",
     "amount": 836613976.85,
     "amount_fmt": "$836.6M"
    },
    {
     "agency": "Department of Homeland Security",
     "amount": 465656173.5,
     "amount_fmt": "$465.7M"
    },
    {
     "agency": "Department of Commerce",
     "amount": 457723255.91,
     "amount_fmt": "$457.7M"
    },
    {
     "agency": "General Services Administration",
     "amount": 81023770.03,
     "amount_fmt": "$81.0M"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=RTX"
  },
  "MSFT": {
   "recipient": "Microsoft Corporation",
   "total_contracts": 2930599316.4599996,
   "total_contracts_fmt": "$2.9B",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 2467411484.97,
     "amount_fmt": "$2.5B"
    },
    {
     "agency": "Department of State",
     "amount": 155172968.58,
     "amount_fmt": "$155.2M"
    },
    {
     "agency": "Department of Justice",
     "amount": 113674667.68,
     "amount_fmt": "$113.7M"
    },
    {
     "agency": "Department of Homeland Security",
     "amount": 96907753.08,
     "amount_fmt": "$96.9M"
    },
    {
     "agency": "Department of Agriculture",
     "amount": 50780492.38,
     "amount_fmt": "$50.8M"
    },
    {
     "agency": "Social Security Administration",
     "amount": 46651949.77,
     "amount_fmt": "$46.7M"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Microsoft%20Corporation"
  },
  "UPS": {
   "recipient": "United Parcel Service",
   "total_contracts": 1479191264.3700004,
   "total_contracts_fmt": "$1.5B",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 687763014.48,
     "amount_fmt": "$687.8M"
    },
    {
     "agency": "Department of Veterans Affairs",
     "amount": 647815127.84,
     "amount_fmt": "$647.8M"
    },
    {
     "agency": "Department of the Treasury",
     "amount": 72437355.24,
     "amount_fmt": "$72.4M"
    },
    {
     "agency": "Social Security Administration",
     "amount": 38628091.89,
     "amount_fmt": "$38.6M"
    },
    {
     "agency": "Department of Health and Human Services",
     "amount": 18532784.03,
     "amount_fmt": "$18.5M"
    },
    {
     "agency": "Department of Homeland Security",
     "amount": 14014890.89,
     "amount_fmt": "$14.0M"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=United%20Parcel%20Service"
  },
  "LOW": {
   "recipient": "Lowe's",
   "total_contracts": 98677.42,
   "total_contracts_fmt": "$99K",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 74464.2,
     "amount_fmt": "$74K"
    },
    {
     "agency": "General Services Administration",
     "amount": 24347.66,
     "amount_fmt": "$24K"
    },
    {
     "agency": "Department of Health and Human Services",
     "amount": -134.44,
     "amount_fmt": "$134"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Lowe%27s"
  },
  "CAT": {
   "recipient": "Caterpillar",
   "total_contracts": 1585795800.09,
   "total_contracts_fmt": "$1.6B",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 1491916201.46,
     "amount_fmt": "$1.5B"
    },
    {
     "agency": "Department of the Interior",
     "amount": 39640011.65,
     "amount_fmt": "$39.6M"
    },
    {
     "agency": "General Services Administration",
     "amount": 20368343.61,
     "amount_fmt": "$20.4M"
    },
    {
     "agency": "Department of Homeland Security",
     "amount": 14004645.86,
     "amount_fmt": "$14.0M"
    },
    {
     "agency": "Department of Agriculture",
     "amount": 11268149.46,
     "amount_fmt": "$11.3M"
    },
    {
     "agency": "Department of State",
     "amount": 8598448.05,
     "amount_fmt": "$8.6M"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Caterpillar"
  },
  "LMT": {
   "recipient": "Lockheed Martin Corporation",
   "total_contracts": 274423448059.18,
   "total_contracts_fmt": "$274.4B",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 272974116269.91,
     "amount_fmt": "$273.0B"
    },
    {
     "agency": "National Aeronautics and Space Administration",
     "amount": 692800759.3,
     "amount_fmt": "$692.8M"
    },
    {
     "agency": "Department of Commerce",
     "amount": 358249471.02,
     "amount_fmt": "$358.2M"
    },
    {
     "agency": "General Services Administration",
     "amount": 204505699.0,
     "amount_fmt": "$204.5M"
    },
    {
     "agency": "Department of Homeland Security",
     "amount": 183444972.16,
     "amount_fmt": "$183.4M"
    },
    {
     "agency": "Department of the Interior",
     "amount": 10330887.79,
     "amount_fmt": "$10.3M"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Lockheed%20Martin%20Corporation"
  },
  "INTC": {
   "recipient": "Intel Corporation",
   "total_contracts": 106274.79,
   "total_contracts_fmt": "$106K",
   "top_agencies": [
    {
     "agency": "National Aeronautics and Space Administration",
     "amount": 84979.5,
     "amount_fmt": "$85K"
    },
    {
     "agency": "Department of Defense",
     "amount": 25000.0,
     "amount_fmt": "$25K"
    },
    {
     "agency": "Department of Energy",
     "amount": -3704.71,
     "amount_fmt": "$4K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Intel%20Corporation"
  },
  "HON": {
   "recipient": "Honeywell International",
   "total_contracts": 31338905922.21,
   "total_contracts_fmt": "$31.3B",
   "top_agencies": [
    {
     "agency": "Department of Energy",
     "amount": 24198837709.25,
     "amount_fmt": "$24.2B"
    },
    {
     "agency": "Department of Defense",
     "amount": 6254297624.73,
     "amount_fmt": "$6.3B"
    },
    {
     "agency": "General Services Administration",
     "amount": 404180374.25,
     "amount_fmt": "$404.2M"
    },
    {
     "agency": "Department of Transportation",
     "amount": 217022923.21,
     "amount_fmt": "$217.0M"
    },
    {
     "agency": "Department of Health and Human Services",
     "amount": 204614810.5,
     "amount_fmt": "$204.6M"
    },
    {
     "agency": "Department of Veterans Affairs",
     "amount": 59952480.27,
     "amount_fmt": "$60.0M"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Honeywell%20International"
  },
  "AXP": {
   "recipient": "American Express Company",
   "total_contracts": 2209869.51,
   "total_contracts_fmt": "$2.2M",
   "top_agencies": [
    {
     "agency": "Executive Office of the President",
     "amount": 2160259.69,
     "amount_fmt": "$2.2M"
    },
    {
     "agency": "Department of State",
     "amount": 49609.82,
     "amount_fmt": "$50K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=American%20Express%20Company"
  },
  "CMCSA": {
   "recipient": "Comcast Corporation",
   "total_contracts": 164552353.36,
   "total_contracts_fmt": "$164.6M",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 111909334.92,
     "amount_fmt": "$111.9M"
    },
    {
     "agency": "Department of Health and Human Services",
     "amount": 25662334.37,
     "amount_fmt": "$25.7M"
    },
    {
     "agency": "Social Security Administration",
     "amount": 10012754.8,
     "amount_fmt": "$10.0M"
    },
    {
     "agency": "Department of Commerce",
     "amount": 6162578.63,
     "amount_fmt": "$6.2M"
    },
    {
     "agency": "Department of Veterans Affairs",
     "amount": 5702304.37,
     "amount_fmt": "$5.7M"
    },
    {
     "agency": "Department of State",
     "amount": 5103046.27,
     "amount_fmt": "$5.1M"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Comcast%20Corporation"
  },
  "KO": {
   "recipient": "The Coca-Cola Company",
   "total_contracts": 21671851.79,
   "total_contracts_fmt": "$21.7M",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 21641950.23,
     "amount_fmt": "$21.6M"
    },
    {
     "agency": "Department of Agriculture",
     "amount": 29901.56,
     "amount_fmt": "$30K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=The%20Coca-Cola%20Company"
  },
  "ABT": {
   "recipient": "Abbott Laboratories",
   "total_contracts": 5112959580.18,
   "total_contracts_fmt": "$5.1B",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 3849127696.74,
     "amount_fmt": "$3.8B"
    },
    {
     "agency": "Department of Veterans Affairs",
     "amount": 641971988.64,
     "amount_fmt": "$642.0M"
    },
    {
     "agency": "Department of Health and Human Services",
     "amount": 581068504.38,
     "amount_fmt": "$581.1M"
    },
    {
     "agency": "Department of Justice",
     "amount": 17828605.09,
     "amount_fmt": "$17.8M"
    },
    {
     "agency": "Department of Homeland Security",
     "amount": 13105558.34,
     "amount_fmt": "$13.1M"
    },
    {
     "agency": "Department of the Interior",
     "amount": 9857226.99,
     "amount_fmt": "$9.9M"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Abbott%20Laboratories"
  },
  "HUM": {
   "recipient": "Humana",
   "total_contracts": 44217764725.619995,
   "total_contracts_fmt": "$44.2B",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 43809414346.34,
     "amount_fmt": "$43.8B"
    },
    {
     "agency": "Department of Veterans Affairs",
     "amount": 408350379.28,
     "amount_fmt": "$408.4M"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Humana"
  },
  "AAPL": {
   "recipient": "Apple",
   "total_contracts": 175392365.53000006,
   "total_contracts_fmt": "$175.4M",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 99705213.37,
     "amount_fmt": "$99.7M"
    },
    {
     "agency": "Department of Homeland Security",
     "amount": 45872621.02,
     "amount_fmt": "$45.9M"
    },
    {
     "agency": "Department of Agriculture",
     "amount": 17041751.05,
     "amount_fmt": "$17.0M"
    },
    {
     "agency": "Department of Justice",
     "amount": 5893074.83,
     "amount_fmt": "$5.9M"
    },
    {
     "agency": "Department of Veterans Affairs",
     "amount": 3655733.55,
     "amount_fmt": "$3.7M"
    },
    {
     "agency": "Department of Commerce",
     "amount": 3223971.71,
     "amount_fmt": "$3.2M"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Apple"
  },
  "MCD": {
   "recipient": "McDonald's Corporation",
   "total_contracts": 0,
   "total_contracts_fmt": null,
   "top_agencies": [],
   "url": "https://www.usaspending.gov/search?keyword=McDonald%27s%20Corporation"
  },
  "BMY": {
   "recipient": "Bristol-Myers Squibb Company",
   "total_contracts": 14212476.62,
   "total_contracts_fmt": "$14.2M",
   "top_agencies": [
    {
     "agency": "Department of Veterans Affairs",
     "amount": 14212476.62,
     "amount_fmt": "$14.2M"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Bristol-Myers%20Squibb%20Company"
  },
  "WHR": {
   "recipient": "Whirlpool Corporation",
   "total_contracts": 0,
   "total_contracts_fmt": null,
   "top_agencies": [],
   "url": "https://www.usaspending.gov/search?keyword=Whirlpool%20Corporation"
  },
  "COF": {
   "recipient": "Capital One Financial Corporation",
   "total_contracts": 0,
   "total_contracts_fmt": null,
   "top_agencies": [],
   "url": "https://www.usaspending.gov/search?keyword=Capital%20One%20Financial%20Corporation"
  },
  "CI": {
   "recipient": "Cigna Corporation",
   "total_contracts": -78833.58,
   "total_contracts_fmt": "$79K",
   "top_agencies": [
    {
     "agency": "Department of the Treasury",
     "amount": -78833.58,
     "amount_fmt": "$79K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Cigna%20Corporation"
  },
  "GOOG": {
   "recipient": "Google",
   "total_contracts": 27670140.339999996,
   "total_contracts_fmt": "$27.7M",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 19341500.88,
     "amount_fmt": "$19.3M"
    },
    {
     "agency": "Department of Agriculture",
     "amount": 7914824.99,
     "amount_fmt": "$7.9M"
    },
    {
     "agency": "U.S. Agency for Global Media",
     "amount": 210267.94,
     "amount_fmt": "$210K"
    },
    {
     "agency": "Department of Justice",
     "amount": 202598.2,
     "amount_fmt": "$203K"
    },
    {
     "agency": "Department of State",
     "amount": 948.33,
     "amount_fmt": "$948"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Google"
  },
  "NKE": {
   "recipient": "Nike",
   "total_contracts": 105260.48,
   "total_contracts_fmt": "$105K",
   "top_agencies": [
    {
     "agency": "Department of Justice",
     "amount": 66042.0,
     "amount_fmt": "$66K"
    },
    {
     "agency": "Department of Defense",
     "amount": 25990.0,
     "amount_fmt": "$26K"
    },
    {
     "agency": "Department of State",
     "amount": 13228.48,
     "amount_fmt": "$13K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Nike"
  },
  "CAG": {
   "recipient": "Conagra Brands",
   "total_contracts": 2697640.73,
   "total_contracts_fmt": "$2.7M",
   "top_agencies": [
    {
     "agency": "Department of Agriculture",
     "amount": 2697640.73,
     "amount_fmt": "$2.7M"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Conagra%20Brands"
  },
  "DVN": {
   "recipient": "Devon Energy Corporation",
   "total_contracts": 0,
   "total_contracts_fmt": null,
   "top_agencies": [],
   "url": "https://www.usaspending.gov/search?keyword=Devon%20Energy%20Corporation"
  },
  "STT": {
   "recipient": "State Street Corporation",
   "total_contracts": 72887794.05999999,
   "total_contracts_fmt": "$72.9M",
   "top_agencies": [
    {
     "agency": "Pension Benefit Guaranty Corporation",
     "amount": 72697004.35,
     "amount_fmt": "$72.7M"
    },
    {
     "agency": "Department of Housing and Urban Development",
     "amount": 190789.71,
     "amount_fmt": "$191K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=State%20Street%20Corporation"
  },
  "PH": {
   "recipient": "Parker-Hannifin Corporation",
   "total_contracts": 1609635293.2000003,
   "total_contracts_fmt": "$1.6B",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 1594594728.19,
     "amount_fmt": "$1.6B"
    },
    {
     "agency": "Department of Homeland Security",
     "amount": 8699795.71,
     "amount_fmt": "$8.7M"
    },
    {
     "agency": "General Services Administration",
     "amount": 5901053.92,
     "amount_fmt": "$5.9M"
    },
    {
     "agency": "National Aeronautics and Space Administration",
     "amount": 238502.8,
     "amount_fmt": "$239K"
    },
    {
     "agency": "Department of Health and Human Services",
     "amount": 179674.18,
     "amount_fmt": "$180K"
    },
    {
     "agency": "Department of Veterans Affairs",
     "amount": 21538.4,
     "amount_fmt": "$22K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Parker-Hannifin%20Corporation"
  },
  "SBUX": {
   "recipient": "Starbucks",
   "total_contracts": 47765.0,
   "total_contracts_fmt": "$48K",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 47765.0,
     "amount_fmt": "$48K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Starbucks"
  },
  "QCOM": {
   "recipient": "QUALCOMM Incorporated",
   "total_contracts": 252329.91999999998,
   "total_contracts_fmt": "$252K",
   "top_agencies": [
    {
     "agency": "Department of Commerce",
     "amount": 347082.29,
     "amount_fmt": "$347K"
    },
    {
     "agency": "National Aeronautics and Space Administration",
     "amount": 30000.0,
     "amount_fmt": "$30K"
    },
    {
     "agency": "Department of Defense",
     "amount": -124752.37,
     "amount_fmt": "$125K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=QUALCOMM%20Incorporated"
  },
  "BSX": {
   "recipient": "Boston Scientific Corp",
   "total_contracts": 167394419.13,
   "total_contracts_fmt": "$167.4M",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 98568502.65,
     "amount_fmt": "$98.6M"
    },
    {
     "agency": "Department of Veterans Affairs",
     "amount": 68587078.13,
     "amount_fmt": "$68.6M"
    },
    {
     "agency": "Department of Health and Human Services",
     "amount": 238838.35,
     "amount_fmt": "$239K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Boston%20Scientific%20Corp"
  },
  "SHW": {
   "recipient": "The Sherwin-Williams Company",
   "total_contracts": 29149741.179999996,
   "total_contracts_fmt": "$29.1M",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 26261508.99,
     "amount_fmt": "$26.3M"
    },
    {
     "agency": "Department of Justice",
     "amount": 2505767.75,
     "amount_fmt": "$2.5M"
    },
    {
     "agency": "Department of State",
     "amount": 211058.63,
     "amount_fmt": "$211K"
    },
    {
     "agency": "Department of Homeland Security",
     "amount": 132965.18,
     "amount_fmt": "$133K"
    },
    {
     "agency": "Department of Health and Human Services",
     "amount": 22043.99,
     "amount_fmt": "$22K"
    },
    {
     "agency": "Department of Commerce",
     "amount": 16396.64,
     "amount_fmt": "$16K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=The%20Sherwin-Williams%20Company"
  },
  "CPB": {
   "recipient": "Campbell Soup Company",
   "total_contracts": 33356473.26,
   "total_contracts_fmt": "$33.4M",
   "top_agencies": [
    {
     "agency": "Department of Agriculture",
     "amount": 33356473.26,
     "amount_fmt": "$33.4M"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Campbell%20Soup%20Company"
  },
  "CHRW": {
   "recipient": "CH Robinson Worldwide",
   "total_contracts": 0,
   "total_contracts_fmt": null,
   "top_agencies": [],
   "url": "https://www.usaspending.gov/search?keyword=CH%20Robinson%20Worldwide"
  },
  "AZO": {
   "recipient": "AutoZone",
   "total_contracts": 10500.0,
   "total_contracts_fmt": "$10K",
   "top_agencies": [
    {
     "agency": "Smithsonian Institution",
     "amount": 10500.0,
     "amount_fmt": "$10K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=AutoZone"
  },
  "AMD": {
   "recipient": "Advanced Micro Devices",
   "total_contracts": 8379615.0,
   "total_contracts_fmt": "$8.4M",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 8379615.0,
     "amount_fmt": "$8.4M"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Advanced%20Micro%20Devices"
  },
  "EME": {
   "recipient": "Emcor Group",
   "total_contracts": 0,
   "total_contracts_fmt": null,
   "top_agencies": [],
   "url": "https://www.usaspending.gov/search?keyword=Emcor%20Group"
  },
  "MU": {
   "recipient": "Micron Technology",
   "total_contracts": 76570.72,
   "total_contracts_fmt": "$77K",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 77702.0,
     "amount_fmt": "$78K"
    },
    {
     "agency": "Department of Health and Human Services",
     "amount": -1131.28,
     "amount_fmt": "$1K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Micron%20Technology"
  },
  "WRB": {
   "recipient": "WR Berkley",
   "total_contracts": 0,
   "total_contracts_fmt": null,
   "top_agencies": [],
   "url": "https://www.usaspending.gov/search?keyword=WR%20Berkley"
  },
  "STZ": {
   "recipient": "Constellation Brands",
   "total_contracts": 0,
   "total_contracts_fmt": null,
   "top_agencies": [],
   "url": "https://www.usaspending.gov/search?keyword=Constellation%20Brands"
  },
  "CLX": {
   "recipient": "The Clorox Company",
   "total_contracts": 0,
   "total_contracts_fmt": null,
   "top_agencies": [],
   "url": "https://www.usaspending.gov/search?keyword=The%20Clorox%20Company"
  },
  "BLK": {
   "recipient": "BlackRock",
   "total_contracts": 20505201.72,
   "total_contracts_fmt": "$20.5M",
   "top_agencies": [
    {
     "agency": "Pension Benefit Guaranty Corporation",
     "amount": 15908978.33,
     "amount_fmt": "$15.9M"
    },
    {
     "agency": "Department of Veterans Affairs",
     "amount": 3444495.0,
     "amount_fmt": "$3.4M"
    },
    {
     "agency": "Department of Health and Human Services",
     "amount": 1013843.87,
     "amount_fmt": "$1.0M"
    },
    {
     "agency": "Department of the Interior",
     "amount": 137884.52,
     "amount_fmt": "$138K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=BlackRock"
  },
  "GILD": {
   "recipient": "Gilead Sciences Inc",
   "total_contracts": 6580990.63,
   "total_contracts_fmt": "$6.6M",
   "top_agencies": [
    {
     "agency": "Department of Veterans Affairs",
     "amount": 7301602.64,
     "amount_fmt": "$7.3M"
    },
    {
     "agency": "Department of Health and Human Services",
     "amount": -720612.01,
     "amount_fmt": "$721K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Gilead%20Sciences%20Inc"
  },
  "NVDA": {
   "recipient": "Nvidia",
   "total_contracts": 1200.0,
   "total_contracts_fmt": "$1K",
   "top_agencies": [
    {
     "agency": "Department of Justice",
     "amount": 1200.0,
     "amount_fmt": "$1K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Nvidia"
  },
  "MA": {
   "recipient": "MasterCard Incorporated",
   "total_contracts": 3916967.3200000003,
   "total_contracts_fmt": "$3.9M",
   "top_agencies": [
    {
     "agency": "Department of the Treasury",
     "amount": 3267464.12,
     "amount_fmt": "$3.3M"
    },
    {
     "agency": "Department of Homeland Security",
     "amount": 326000.0,
     "amount_fmt": "$326K"
    },
    {
     "agency": "Commodity Futures Trading Commission",
     "amount": 191100.0,
     "amount_fmt": "$191K"
    },
    {
     "agency": "Department of Defense",
     "amount": 58235.0,
     "amount_fmt": "$58K"
    },
    {
     "agency": "Department of Justice",
     "amount": 46931.0,
     "amount_fmt": "$47K"
    },
    {
     "agency": "Securities and Exchange Commission",
     "amount": 27237.2,
     "amount_fmt": "$27K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=MasterCard%20Incorporated"
  },
  "SNDK": {
   "recipient": "SanDisk",
   "total_contracts": 0,
   "total_contracts_fmt": null,
   "top_agencies": [],
   "url": "https://www.usaspending.gov/search?keyword=SanDisk"
  },
  "BIIB": {
   "recipient": "Biogen Idec",
   "total_contracts": 0,
   "total_contracts_fmt": null,
   "top_agencies": [],
   "url": "https://www.usaspending.gov/search?keyword=Biogen%20Idec"
  },
  "ADBE": {
   "recipient": "Adobe",
   "total_contracts": 915629.1599999999,
   "total_contracts_fmt": "$916K",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 761168.4,
     "amount_fmt": "$761K"
    },
    {
     "agency": "National Gallery of Art",
     "amount": 59219.06,
     "amount_fmt": "$59K"
    },
    {
     "agency": "Agency for International Development",
     "amount": 37256.04,
     "amount_fmt": "$37K"
    },
    {
     "agency": "Department of Justice",
     "amount": 30730.46,
     "amount_fmt": "$31K"
    },
    {
     "agency": "U.S. Agency for Global Media",
     "amount": 28255.2,
     "amount_fmt": "$28K"
    },
    {
     "agency": "National Science Foundation",
     "amount": -1000.0,
     "amount_fmt": "$1K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Adobe"
  },
  "EA": {
   "recipient": "Electronic Arts",
   "total_contracts": 0,
   "total_contracts_fmt": null,
   "top_agencies": [],
   "url": "https://www.usaspending.gov/search?keyword=Electronic%20Arts"
  },
  "ADI": {
   "recipient": "Analog Devices",
   "total_contracts": 889668.0,
   "total_contracts_fmt": "$890K",
   "top_agencies": [
    {
     "agency": "Department of State",
     "amount": 536641.0,
     "amount_fmt": "$537K"
    },
    {
     "agency": "Department of Homeland Security",
     "amount": 211875.0,
     "amount_fmt": "$212K"
    },
    {
     "agency": "Department of Energy",
     "amount": 133440.0,
     "amount_fmt": "$133K"
    },
    {
     "agency": "Department of Agriculture",
     "amount": 4376.0,
     "amount_fmt": "$4K"
    },
    {
     "agency": "Department of the Interior",
     "amount": 1668.0,
     "amount_fmt": "$2K"
    },
    {
     "agency": "National Aeronautics and Space Administration",
     "amount": 1668.0,
     "amount_fmt": "$2K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Analog%20Devices"
  },
  "INTU": {
   "recipient": "Intuit",
   "total_contracts": 2507749679.61,
   "total_contracts_fmt": "$2.5B",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 1816683468.04,
     "amount_fmt": "$1.8B"
    },
    {
     "agency": "National Aeronautics and Space Administration",
     "amount": 378119334.9,
     "amount_fmt": "$378.1M"
    },
    {
     "agency": "Department of Veterans Affairs",
     "amount": 239811333.3,
     "amount_fmt": "$239.8M"
    },
    {
     "agency": "Department of Homeland Security",
     "amount": 51578567.18,
     "amount_fmt": "$51.6M"
    },
    {
     "agency": "Small Business Administration",
     "amount": 11812375.77,
     "amount_fmt": "$11.8M"
    },
    {
     "agency": "Department of Energy",
     "amount": 9744600.42,
     "amount_fmt": "$9.7M"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Intuit"
  },
  "TSCO": {
   "recipient": "Tractor Supply Company",
   "total_contracts": 0,
   "total_contracts_fmt": null,
   "top_agencies": [],
   "url": "https://www.usaspending.gov/search?keyword=Tractor%20Supply%20Company"
  },
  "PWR": {
   "recipient": "Quanta Services",
   "total_contracts": 291706895.80999994,
   "total_contracts_fmt": "$291.7M",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 270694214.28,
     "amount_fmt": "$270.7M"
    },
    {
     "agency": "Department of Agriculture",
     "amount": 20877609.58,
     "amount_fmt": "$20.9M"
    },
    {
     "agency": "Department of Justice",
     "amount": 87561.87,
     "amount_fmt": "$88K"
    },
    {
     "agency": "Department of Homeland Security",
     "amount": 26137.33,
     "amount_fmt": "$26K"
    },
    {
     "agency": "Department of Transportation",
     "amount": 18170.55,
     "amount_fmt": "$18K"
    },
    {
     "agency": "General Services Administration",
     "amount": 3202.2,
     "amount_fmt": "$3K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Quanta%20Services"
  },
  "HUBB": {
   "recipient": "Hubbell Inc",
   "total_contracts": 247968.0,
   "total_contracts_fmt": "$248K",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 119664.0,
     "amount_fmt": "$120K"
    },
    {
     "agency": "National Aeronautics and Space Administration",
     "amount": 88304.0,
     "amount_fmt": "$88K"
    },
    {
     "agency": "Department of the Interior",
     "amount": 40000.0,
     "amount_fmt": "$40K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Hubbell%20Inc"
  },
  "MKL": {
   "recipient": "Markel Corp",
   "total_contracts": 3922624.99,
   "total_contracts_fmt": "$3.9M",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 2370704.63,
     "amount_fmt": "$2.4M"
    },
    {
     "agency": "Department of the Interior",
     "amount": 1283009.2,
     "amount_fmt": "$1.3M"
    },
    {
     "agency": "National Aeronautics and Space Administration",
     "amount": 229763.0,
     "amount_fmt": "$230K"
    },
    {
     "agency": "Department of Veterans Affairs",
     "amount": 39188.16,
     "amount_fmt": "$39K"
    },
    {
     "agency": "Department of Transportation",
     "amount": -40.0,
     "amount_fmt": "$40"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Markel%20Corp"
  },
  "SCI": {
   "recipient": "Service Corp International",
   "total_contracts": 0,
   "total_contracts_fmt": null,
   "top_agencies": [],
   "url": "https://www.usaspending.gov/search?keyword=Service%20Corp%20International"
  },
  "PKG": {
   "recipient": "Packaging Corp of America",
   "total_contracts": 0,
   "total_contracts_fmt": null,
   "top_agencies": [],
   "url": "https://www.usaspending.gov/search?keyword=Packaging%20Corp%20of%20America"
  },
  "MLM": {
   "recipient": "Martin Marietta Materials",
   "total_contracts": 1174109.74,
   "total_contracts_fmt": "$1.2M",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 1232923.07,
     "amount_fmt": "$1.2M"
    },
    {
     "agency": "Department of Agriculture",
     "amount": -3520.02,
     "amount_fmt": "$4K"
    },
    {
     "agency": "Department of the Interior",
     "amount": -55293.31,
     "amount_fmt": "$55K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Martin%20Marietta%20Materials"
  },
  "ROP": {
   "recipient": "Roper Industries",
   "total_contracts": 0,
   "total_contracts_fmt": null,
   "top_agencies": [],
   "url": "https://www.usaspending.gov/search?keyword=Roper%20Industries"
  },
  "CVS": {
   "recipient": "CVS Health Corporation",
   "total_contracts": 630287036.78,
   "total_contracts_fmt": "$630.3M",
   "top_agencies": [
    {
     "agency": "Department of Health and Human Services",
     "amount": 613766422.86,
     "amount_fmt": "$613.8M"
    },
    {
     "agency": "Executive Office of the President",
     "amount": 15005000.0,
     "amount_fmt": "$15.0M"
    },
    {
     "agency": "Department of Veterans Affairs",
     "amount": 1422441.62,
     "amount_fmt": "$1.4M"
    },
    {
     "agency": "Department of Justice",
     "amount": 41622.3,
     "amount_fmt": "$42K"
    },
    {
     "agency": "Department of Agriculture",
     "amount": 31570.0,
     "amount_fmt": "$32K"
    },
    {
     "agency": "Environmental Protection Agency",
     "amount": 19980.0,
     "amount_fmt": "$20K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=CVS%20Health%20Corporation"
  },
  "CB": {
   "recipient": "The Chubb Corporation",
   "total_contracts": 0,
   "total_contracts_fmt": null,
   "top_agencies": [],
   "url": "https://www.usaspending.gov/search?keyword=The%20Chubb%20Corporation"
  },
  "V": {
   "recipient": "VISA",
   "total_contracts": 69962806.03999999,
   "total_contracts_fmt": "$70.0M",
   "top_agencies": [
    {
     "agency": "Department of Homeland Security",
     "amount": 50386353.12,
     "amount_fmt": "$50.4M"
    },
    {
     "agency": "Department of Defense",
     "amount": 9559716.32,
     "amount_fmt": "$9.6M"
    },
    {
     "agency": "Department of Justice",
     "amount": 5923598.15,
     "amount_fmt": "$5.9M"
    },
    {
     "agency": "Department of Veterans Affairs",
     "amount": 3711034.85,
     "amount_fmt": "$3.7M"
    },
    {
     "agency": "Department of the Interior",
     "amount": 220496.6,
     "amount_fmt": "$220K"
    },
    {
     "agency": "Department of Health and Human Services",
     "amount": 161607.0,
     "amount_fmt": "$162K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=VISA"
  },
  "TSLA": {
   "recipient": "Tesla",
   "total_contracts": 64801979.83,
   "total_contracts_fmt": "$64.8M",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 28297584.52,
     "amount_fmt": "$28.3M"
    },
    {
     "agency": "National Aeronautics and Space Administration",
     "amount": 15744147.17,
     "amount_fmt": "$15.7M"
    },
    {
     "agency": "Department of Commerce",
     "amount": 10211130.25,
     "amount_fmt": "$10.2M"
    },
    {
     "agency": "Department of Homeland Security",
     "amount": 4498024.77,
     "amount_fmt": "$4.5M"
    },
    {
     "agency": "Department of Veterans Affairs",
     "amount": 3536027.7,
     "amount_fmt": "$3.5M"
    },
    {
     "agency": "Department of State",
     "amount": 2515065.42,
     "amount_fmt": "$2.5M"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Tesla"
  },
  "LLY": {
   "recipient": "Eli Lilly & Co",
   "total_contracts": 0,
   "total_contracts_fmt": null,
   "top_agencies": [],
   "url": "https://www.usaspending.gov/search?keyword=Eli%20Lilly%20%26%20Co"
  },
  "MDT": {
   "recipient": "Medtronic Inc",
   "total_contracts": 302956222.60999995,
   "total_contracts_fmt": "$303.0M",
   "top_agencies": [
    {
     "agency": "Department of Veterans Affairs",
     "amount": 215248848.24,
     "amount_fmt": "$215.2M"
    },
    {
     "agency": "Department of Defense",
     "amount": 84457978.16,
     "amount_fmt": "$84.5M"
    },
    {
     "agency": "Department of Health and Human Services",
     "amount": 1873854.87,
     "amount_fmt": "$1.9M"
    },
    {
     "agency": "General Services Administration",
     "amount": 1337610.0,
     "amount_fmt": "$1.3M"
    },
    {
     "agency": "Department of Justice",
     "amount": 24931.34,
     "amount_fmt": "$25K"
    },
    {
     "agency": "Department of Agriculture",
     "amount": 13000.0,
     "amount_fmt": "$13K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Medtronic%20Inc"
  },
  "PYPL": {
   "recipient": "PayPal",
   "total_contracts": 0,
   "total_contracts_fmt": null,
   "top_agencies": [],
   "url": "https://www.usaspending.gov/search?keyword=PayPal"
  },
  "RRC": {
   "recipient": "Range Resources Corporation",
   "total_contracts": 0,
   "total_contracts_fmt": null,
   "top_agencies": [],
   "url": "https://www.usaspending.gov/search?keyword=Range%20Resources%20Corporation"
  },
  "AMT": {
   "recipient": "American Tower",
   "total_contracts": 10807693.829999998,
   "total_contracts_fmt": "$10.8M",
   "top_agencies": [
    {
     "agency": "Department of Justice",
     "amount": 4517301.79,
     "amount_fmt": "$4.5M"
    },
    {
     "agency": "Department of Homeland Security",
     "amount": 2485816.49,
     "amount_fmt": "$2.5M"
    },
    {
     "agency": "Department of the Treasury",
     "amount": 1816489.81,
     "amount_fmt": "$1.8M"
    },
    {
     "agency": "Department of State",
     "amount": 1038407.19,
     "amount_fmt": "$1.0M"
    },
    {
     "agency": "Department of Defense",
     "amount": 685920.6,
     "amount_fmt": "$686K"
    },
    {
     "agency": "Department of the Interior",
     "amount": 263757.95,
     "amount_fmt": "$264K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=American%20Tower"
  },
  "NFLX": {
   "recipient": "Netflix",
   "total_contracts": 0,
   "total_contracts_fmt": null,
   "top_agencies": [],
   "url": "https://www.usaspending.gov/search?keyword=Netflix"
  },
  "NEE": {
   "recipient": "NextEra Energy Inc",
   "total_contracts": 0,
   "total_contracts_fmt": null,
   "top_agencies": [],
   "url": "https://www.usaspending.gov/search?keyword=NextEra%20Energy%20Inc"
  },
  "ENB": {
   "recipient": "Enbridge",
   "total_contracts": 278844.5,
   "total_contracts_fmt": "$279K",
   "top_agencies": [
    {
     "agency": "Department of Veterans Affairs",
     "amount": 298344.66,
     "amount_fmt": "$298K"
    },
    {
     "agency": "Department of Defense",
     "amount": -19500.16,
     "amount_fmt": "$20K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Enbridge"
  },
  "ST": {
   "recipient": "Sensata Technologies Holding N.V.",
   "total_contracts": 0,
   "total_contracts_fmt": null,
   "top_agencies": [],
   "url": "https://www.usaspending.gov/search?keyword=Sensata%20Technologies%20Holding%20N.V."
  },
  "TRMB": {
   "recipient": "Trimble",
   "total_contracts": 85172136.08999999,
   "total_contracts_fmt": "$85.2M",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 34226711.44,
     "amount_fmt": "$34.2M"
    },
    {
     "agency": "Department of Agriculture",
     "amount": 33868028.61,
     "amount_fmt": "$33.9M"
    },
    {
     "agency": "Department of the Interior",
     "amount": 9726661.13,
     "amount_fmt": "$9.7M"
    },
    {
     "agency": "Department of Commerce",
     "amount": 5309955.94,
     "amount_fmt": "$5.3M"
    },
    {
     "agency": "General Services Administration",
     "amount": 1141665.28,
     "amount_fmt": "$1.1M"
    },
    {
     "agency": "Department of Health and Human Services",
     "amount": 899113.69,
     "amount_fmt": "$899K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Trimble"
  },
  "MELI": {
   "recipient": "MercadoLibre",
   "total_contracts": 0,
   "total_contracts_fmt": null,
   "top_agencies": [],
   "url": "https://www.usaspending.gov/search?keyword=MercadoLibre"
  },
  "REGN": {
   "recipient": "Regeneron Pharmaceuticals",
   "total_contracts": 6198797148.66,
   "total_contracts_fmt": "$6.2B",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 5565000000.0,
     "amount_fmt": "$5.6B"
    },
    {
     "agency": "Department of Health and Human Services",
     "amount": 633154824.9,
     "amount_fmt": "$633.2M"
    },
    {
     "agency": "Department of Veterans Affairs",
     "amount": 642323.76,
     "amount_fmt": "$642K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Regeneron%20Pharmaceuticals"
  },
  "VRSK": {
   "recipient": "Verisk Analytics",
   "total_contracts": 90025416.11999999,
   "total_contracts_fmt": "$90.0M",
   "top_agencies": [
    {
     "agency": "Department of Homeland Security",
     "amount": 47680331.44,
     "amount_fmt": "$47.7M"
    },
    {
     "agency": "Department of Defense",
     "amount": 23916108.64,
     "amount_fmt": "$23.9M"
    },
    {
     "agency": "Department of Health and Human Services",
     "amount": 12355014.66,
     "amount_fmt": "$12.4M"
    },
    {
     "agency": "Department of the Treasury",
     "amount": 3851964.16,
     "amount_fmt": "$3.9M"
    },
    {
     "agency": "Department of Energy",
     "amount": 1675620.22,
     "amount_fmt": "$1.7M"
    },
    {
     "agency": "Department of Commerce",
     "amount": 546377.0,
     "amount_fmt": "$546K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Verisk%20Analytics"
  },
  "ABBV": {
   "recipient": "AbbVie",
   "total_contracts": 2760165.43,
   "total_contracts_fmt": "$2.8M",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 1449725.07,
     "amount_fmt": "$1.4M"
    },
    {
     "agency": "Department of Veterans Affairs",
     "amount": 1180223.71,
     "amount_fmt": "$1.2M"
    },
    {
     "agency": "Department of Health and Human Services",
     "amount": 130216.65,
     "amount_fmt": "$130K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=AbbVie"
  },
  "COO": {
   "recipient": "Cooper Companies (The)",
   "total_contracts": 0,
   "total_contracts_fmt": null,
   "top_agencies": [],
   "url": "https://www.usaspending.gov/search?keyword=Cooper%20Companies%20%28The%29"
  },
  "GIL": {
   "recipient": "Gildan Activewear",
   "total_contracts": 0,
   "total_contracts_fmt": null,
   "top_agencies": [],
   "url": "https://www.usaspending.gov/search?keyword=Gildan%20Activewear"
  },
  "TEL": {
   "recipient": "TE Connectivity Ltd.",
   "total_contracts": 40485414.95999999,
   "total_contracts_fmt": "$40.5M",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 37405322.78,
     "amount_fmt": "$37.4M"
    },
    {
     "agency": "National Aeronautics and Space Administration",
     "amount": 2592804.98,
     "amount_fmt": "$2.6M"
    },
    {
     "agency": "Department of the Interior",
     "amount": 311544.8,
     "amount_fmt": "$312K"
    },
    {
     "agency": "Department of Transportation",
     "amount": 98464.0,
     "amount_fmt": "$98K"
    },
    {
     "agency": "Department of Homeland Security",
     "amount": 70900.0,
     "amount_fmt": "$71K"
    },
    {
     "agency": "General Services Administration",
     "amount": 6378.4,
     "amount_fmt": "$6K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=TE%20Connectivity%20Ltd."
  },
  "TDG": {
   "recipient": "Transdigm Group Incorporated",
   "total_contracts": 1925072995.18,
   "total_contracts_fmt": "$1.9B",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 1885148408.65,
     "amount_fmt": "$1.9B"
    },
    {
     "agency": "Department of Homeland Security",
     "amount": 22083358.03,
     "amount_fmt": "$22.1M"
    },
    {
     "agency": "National Aeronautics and Space Administration",
     "amount": 16139820.16,
     "amount_fmt": "$16.1M"
    },
    {
     "agency": "Department of the Interior",
     "amount": 874115.0,
     "amount_fmt": "$874K"
    },
    {
     "agency": "Department of Agriculture",
     "amount": 719968.0,
     "amount_fmt": "$720K"
    },
    {
     "agency": "Department of Transportation",
     "amount": 107325.34,
     "amount_fmt": "$107K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Transdigm%20Group%20Incorporated"
  },
  "PANW": {
   "recipient": "Palo Alto Networks",
   "total_contracts": 6738084.67,
   "total_contracts_fmt": "$6.7M",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 7209943.42,
     "amount_fmt": "$7.2M"
    },
    {
     "agency": "Securities and Exchange Commission",
     "amount": -471858.75,
     "amount_fmt": "$472K"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Palo%20Alto%20Networks"
  },
  "FN": {
   "recipient": "First National Financial Corporation",
   "total_contracts": 0,
   "total_contracts_fmt": null,
   "top_agencies": [],
   "url": "https://www.usaspending.gov/search?keyword=First%20National%20Financial%20Corporation"
  },
  "TPH": {
   "recipient": "Temple Hotels Inc",
   "total_contracts": 0,
   "total_contracts_fmt": null,
   "top_agencies": [],
   "url": "https://www.usaspending.gov/search?keyword=Temple%20Hotels%20Inc"
  },
  "TMO": {
   "recipient": "Thermo Fisher Scientific",
   "total_contracts": 507090695.99,
   "total_contracts_fmt": "$507.1M",
   "top_agencies": [
    {
     "agency": "Department of Health and Human Services",
     "amount": 319988298.43,
     "amount_fmt": "$320.0M"
    },
    {
     "agency": "Department of Justice",
     "amount": 82948630.12,
     "amount_fmt": "$82.9M"
    },
    {
     "agency": "Department of Defense",
     "amount": 39808919.38,
     "amount_fmt": "$39.8M"
    },
    {
     "agency": "Department of Commerce",
     "amount": 33297745.57,
     "amount_fmt": "$33.3M"
    },
    {
     "agency": "Department of Veterans Affairs",
     "amount": 17114144.49,
     "amount_fmt": "$17.1M"
    },
    {
     "agency": "Department of Agriculture",
     "amount": 13932958.0,
     "amount_fmt": "$13.9M"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Thermo%20Fisher%20Scientific"
  },
  "IAG": {
   "recipient": "Industrial Alliance Insurance And Financial Services",
   "total_contracts": 0,
   "total_contracts_fmt": null,
   "top_agencies": [],
   "url": "https://www.usaspending.gov/search?keyword=Industrial%20Alliance%20Insurance%20And%20Financial%20Services"
  },
  "CLH": {
   "recipient": "Clean Harbors Inc",
   "total_contracts": 0,
   "total_contracts_fmt": null,
   "top_agencies": [],
   "url": "https://www.usaspending.gov/search?keyword=Clean%20Harbors%20Inc"
  },
  "FLEX": {
   "recipient": "Flex Ltd.",
   "total_contracts": 0,
   "total_contracts_fmt": null,
   "top_agencies": [],
   "url": "https://www.usaspending.gov/search?keyword=Flex%20Ltd."
  },
  "CVNA": {
   "recipient": "Carvana Company",
   "total_contracts": 0,
   "total_contracts_fmt": null,
   "top_agencies": [],
   "url": "https://www.usaspending.gov/search?keyword=Carvana%20Company"
  },
  "CARR": {
   "recipient": "Carrier Global Corporation",
   "total_contracts": 172979645.12,
   "total_contracts_fmt": "$173.0M",
   "top_agencies": [
    {
     "agency": "Department of Defense",
     "amount": 88780367.49,
     "amount_fmt": "$88.8M"
    },
    {
     "agency": "Department of Veterans Affairs",
     "amount": 55214052.51,
     "amount_fmt": "$55.2M"
    },
    {
     "agency": "General Services Administration",
     "amount": 8979532.96,
     "amount_fmt": "$9.0M"
    },
    {
     "agency": "Department of Justice",
     "amount": 8861378.0,
     "amount_fmt": "$8.9M"
    },
    {
     "agency": "Smithsonian Institution",
     "amount": 6068153.0,
     "amount_fmt": "$6.1M"
    },
    {
     "agency": "Department of Homeland Security",
     "amount": 5076161.16,
     "amount_fmt": "$5.1M"
    }
   ],
   "url": "https://www.usaspending.gov/search?keyword=Carrier%20Global%20Corporation"
  },
  "CTRA": {
   "recipient": "Coterra Energy",
   "total_contracts": 0,
   "total_contracts_fmt": null,
   "top_agencies": [],
   "url": "https://www.usaspending.gov/search?keyword=Coterra%20Energy"
  },
  "BWXT": {
   "recipient": "BWXT Advanced Technologies Inc",
   "total_contracts": 0,
   "total_contracts_fmt": null,
   "top_agencies": [],
   "url": "https://www.usaspending.gov/search?keyword=BWXT%20Advanced%20Technologies%20Inc"
  }
 },
 "count": 108
};
