"""ThinkFree - BLS regional CPI (inflation burden) enrichment.

Adds year-over-year inflation by Census region (BLS CPI) to each state in
webapp/js/states_data.js and folds inflation into the Pressure score.

BLS_API_KEY read from .env. One API call covers all four regions.

Run:  ./tf_env/bin/python webapp/build_bls.py  (after build_states/census/bea)
"""
from __future__ import annotations

import json
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STATES_JS = Path(__file__).resolve().parent / "js" / "states_data.js"

KEY = None
for _l in open(ROOT / ".env", encoding="utf-8"):
    if _l.startswith("BLS_API_KEY="):
        KEY = _l.strip().split("=", 1)[1]

REGION_SERIES = {
    "Northeast": "CUUR0100SA0", "Midwest": "CUUR0200SA0",
    "South": "CUUR0300SA0", "West": "CUUR0400SA0",
}
STATE_REGION = {
    # Northeast
    "CT": "Northeast", "ME": "Northeast", "MA": "Northeast", "NH": "Northeast", "RI": "Northeast",
    "VT": "Northeast", "NJ": "Northeast", "NY": "Northeast", "PA": "Northeast",
    # Midwest
    "IL": "Midwest", "IN": "Midwest", "MI": "Midwest", "OH": "Midwest", "WI": "Midwest",
    "IA": "Midwest", "KS": "Midwest", "MN": "Midwest", "MO": "Midwest", "NE": "Midwest",
    "ND": "Midwest", "SD": "Midwest",
    # South
    "DE": "South", "FL": "South", "GA": "South", "MD": "South", "NC": "South", "SC": "South",
    "VA": "South", "DC": "South", "WV": "South", "AL": "South", "KY": "South", "MS": "South",
    "TN": "South", "AR": "South", "LA": "South", "OK": "South", "TX": "South",
    # West
    "AZ": "West", "CO": "West", "ID": "West", "MT": "West", "NV": "West", "NM": "West",
    "UT": "West", "WY": "West", "AK": "West", "CA": "West", "HI": "West", "OR": "West", "WA": "West",
}


def clamp(v, lo=0, hi=100):
    return max(lo, min(hi, v))


def main():
    if not KEY:
        print("ERROR: BLS_API_KEY missing")
        return
    if not STATES_JS.exists():
        print("ERROR: run build_states.py first")
        return
    s = STATES_JS.read_text(encoding="utf-8")
    data = json.loads(s[s.index("{"): s.rindex("}") + 1])
    out = data["byState"]

    body = json.dumps({"seriesid": list(REGION_SERIES.values()),
                       "startyear": "2023", "endyear": "2025", "registrationkey": KEY}).encode()
    req = urllib.request.Request("https://api.bls.gov/publicAPI/v2/timeseries/data/",
                                 data=body, headers={"Content-Type": "application/json", "User-Agent": "ThinkFree/1.0"})
    print("Fetching BLS regional CPI...")
    with urllib.request.urlopen(req, timeout=30) as r:
        d = json.load(r)
    sid_to_region = {v: k for k, v in REGION_SERIES.items()}
    region_infl = {}
    for ser in d.get("Results", {}).get("series", []):
        obs = ser.get("data", [])
        if len(obs) >= 13:
            cur, yr = float(obs[0]["value"]), float(obs[12]["value"])
            region_infl[sid_to_region[ser["seriesID"]]] = round((cur - yr) / yr * 100, 1)
    print("  regional inflation:", region_infl)

    for ab, v in out.items():
        region = STATE_REGION.get(ab)
        infl = region_infl.get(region)
        if infl is None:
            continue
        v["region"] = region
        v["inflation"] = infl
        # inflation above ~2% target adds pressure
        extra = clamp((infl - 2.0) * 6, 0, 16)
        v["pressure_score"] = round(clamp((v.get("pressure_score") or 0) + extra))

    data["source"] = data.get("source", "") + " + BLS CPI"
    with open(STATES_JS, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by build_states/census/bea/bls. No API key stored here.\n")
        f.write("window.STATES_DATA = ")
        json.dump(data, f, ensure_ascii=False, indent=1)
        f.write(";\n")
    print(f"\nupdated {STATES_JS} ({STATES_JS.stat().st_size//1024} KB)")


if __name__ == "__main__":
    main()
