"""ThinkFree - Congress.gov per-member legislative activity.

The hover cards showed a misleading "0-1 bills" (only trade-correlated bills).
This pulls each tracked member's REAL sponsored + cosponsored legislation counts
from the Congress.gov API, keyed by bioguide id, so every member shows true
legislative activity.

CONGRESS_API_KEY is read from .env and never written to output or logs.
Writes webapp/js/member_bills.js  (window.MEMBER_BILLS).

Run:  ./tf_env/bin/python webapp/build_member_bills.py
Docs: https://api.congress.gov/
"""
from __future__ import annotations

import json
import time
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
JS = Path(__file__).resolve().parent / "js"
OUT = JS / "member_bills.js"
BASE = "https://api.congress.gov/v3/member/"
SLEEP = 0.25

KEY = None
for _l in open(ROOT / ".env", encoding="utf-8"):
    if _l.startswith("CONGRESS_API_KEY="):
        KEY = _l.strip().split("=", 1)[1]


def politicians():
    t = (JS / "data.js").read_text(encoding="utf-8")
    d = json.loads(t.split("window.TF_DATA =", 1)[1].rstrip().rstrip(";"))
    return d.get("politicians", [])


def count(bioguide, kind):
    url = f"{BASE}{bioguide}/{kind}?limit=1&api_key={KEY}"
    req = urllib.request.Request(url, headers={"User-Agent": "ThinkFree/1.0"})
    with urllib.request.urlopen(req, timeout=25) as r:
        return json.load(r).get("pagination", {}).get("count", 0)


def main():
    if not KEY:
        print("ERROR: CONGRESS_API_KEY missing from .env")
        return
    pols = [p for p in politicians() if p.get("bioguide")]
    print(f"Fetching legislative activity for {len(pols)} members...")
    out = {}
    for p in pols:
        bg = p["bioguide"]
        try:
            spon = count(bg, "sponsored-legislation"); time.sleep(SLEEP)
            cospon = count(bg, "cosponsored-legislation"); time.sleep(SLEEP)
            out[bg] = {"sponsored": spon, "cosponsored": cospon, "total": spon + cospon}
            print(f"  + {bg} {p.get('name','')[:22]:24} sponsored {spon:>4} | cosponsored {cospon:>5}")
        except Exception as e:  # noqa: BLE001
            print(f"  x {bg} {p.get('name','')}: {e}")

    data = {"source": "Congress.gov API", "byBioguide": out, "count": len(out)}
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by webapp/build_member_bills.py (Congress.gov). No API key stored here.\n")
        f.write("window.MEMBER_BILLS = ")
        json.dump(data, f, ensure_ascii=False, indent=1)
        f.write(";\n")
    print(f"\nwrote {OUT} ({OUT.stat().st_size // 1024} KB) - {len(out)} members")


if __name__ == "__main__":
    main()
