"""ThinkFree - BEA Regional Price Parities (cost of living) enrichment.

Adds real cost-of-living (Regional Price Parity, US=100) per state from the
BEA Regional dataset to webapp/js/states_data.js, computes real purchasing
power, and folds cost of living into the prosperity/pressure scores.

BEA_API_KEY read from .env. One API call covers all states.

Run:  ./tf_env/bin/python webapp/build_bea.py   (after build_states + build_census)
"""
from __future__ import annotations

import json
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STATES_JS = Path(__file__).resolve().parent / "js" / "states_data.js"
YEAR = 2023

KEY = None
for _l in open(ROOT / ".env", encoding="utf-8"):
    if _l.startswith("BEA_API_KEY="):
        KEY = _l.strip().split("=", 1)[1]

NAME_TO_AB = {
    "Alabama": "AL", "Alaska": "AK", "Arizona": "AZ", "Arkansas": "AR", "California": "CA",
    "Colorado": "CO", "Connecticut": "CT", "Delaware": "DE", "Florida": "FL", "Georgia": "GA",
    "Hawaii": "HI", "Idaho": "ID", "Illinois": "IL", "Indiana": "IN", "Iowa": "IA",
    "Kansas": "KS", "Kentucky": "KY", "Louisiana": "LA", "Maine": "ME", "Maryland": "MD",
    "Massachusetts": "MA", "Michigan": "MI", "Minnesota": "MN", "Mississippi": "MS", "Missouri": "MO",
    "Montana": "MT", "Nebraska": "NE", "Nevada": "NV", "New Hampshire": "NH", "New Jersey": "NJ",
    "New Mexico": "NM", "New York": "NY", "North Carolina": "NC", "North Dakota": "ND", "Ohio": "OH",
    "Oklahoma": "OK", "Oregon": "OR", "Pennsylvania": "PA", "Rhode Island": "RI", "South Carolina": "SC",
    "South Dakota": "SD", "Tennessee": "TN", "Texas": "TX", "Utah": "UT", "Vermont": "VT",
    "Virginia": "VA", "Washington": "WA", "West Virginia": "WV", "Wisconsin": "WI", "Wyoming": "WY",
    "District of Columbia": "DC",
}


def clamp(v, lo=0, hi=100):
    return max(lo, min(hi, v))


def main():
    if not KEY:
        print("ERROR: BEA_API_KEY missing")
        return
    if not STATES_JS.exists():
        print("ERROR: run build_states.py + build_census.py first")
        return
    s = STATES_JS.read_text(encoding="utf-8")
    data = json.loads(s[s.index("{"): s.rindex("}") + 1])
    out = data["byState"]

    url = (f"https://apps.bea.gov/api/data?&UserID={KEY}&method=GetData&datasetname=Regional"
           f"&TableName=SARPP&LineCode=1&GeoFips=STATE&Year={YEAR}&ResultFormat=json")
    print(f"Fetching BEA Regional Price Parities {YEAR}...")
    req = urllib.request.Request(url, headers={"User-Agent": "ThinkFree/1.0"})
    with urllib.request.urlopen(req, timeout=30) as r:
        rows = json.load(r).get("BEAAPI", {}).get("Results", {}).get("Data", [])

    for row in rows:
        ab = NAME_TO_AB.get(row.get("GeoName"))
        if not ab or ab not in out:
            continue
        try:
            rpp = float(row.get("DataValue"))
        except (ValueError, TypeError):
            continue
        rec = out[ab]
        rec["cost_of_living"] = round(rpp, 1)         # US = 100
        inc = rec.get("median_household_income")
        if inc:
            rec["real_purchasing_power"] = round(inc / (rpp / 100))
        print(f"  + {ab}: RPP {rpp:.1f} | real income ${rec.get('real_purchasing_power', 'n/a')}")

    # fold cost of living into scores
    for ab, v in out.items():
        rpp = v.get("cost_of_living")
        if rpp is None:
            continue
        # extra pressure when cost of living is above national average
        extra_pressure = clamp((rpp - 100) * 1.2, 0, 18)
        v["pressure_score"] = round(clamp((v.get("pressure_score") or 0) + extra_pressure))
        # prosperity uses real purchasing power instead of nominal where available
        rpp_low = v.get("real_purchasing_power")
        if rpp_low:
            # mild bonus/penalty vs ~$70k real income baseline
            adj = clamp((rpp_low - 70000) / 70000 * 10, -8, 8)
            v["prosperity_score"] = round(clamp((v.get("prosperity_score") or 0) + adj))

    data["source"] = "FRED + Census ACS + BEA RPP " + str(YEAR)
    with open(STATES_JS, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by build_states + build_census + build_bea. No API key stored here.\n")
        f.write("window.STATES_DATA = ")
        json.dump(data, f, ensure_ascii=False, indent=1)
        f.write(";\n")
    print(f"\nupdated {STATES_JS} ({STATES_JS.stat().st_size//1024} KB)")


if __name__ == "__main__":
    main()
