"""ThinkFree - SEC-API (sec-api.io) fetcher.

Pulls current Directors & Board Members and the latest annual filing for each
company InfluenceWeb tracks. Writes webapp/js/sec_data.js (window.SEC_DATA).

API key read from .env (SECAPI_IO_KEY); never written to output or logs.

Run:  ./tf_env/bin/python webapp/build_sec.py
Docs: https://sec-api.io/docs
"""
from __future__ import annotations

import gzip
import json
import time
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = Path(__file__).resolve().parent / "js" / "sec_data.js"

KEY = None
for _l in open(ROOT / ".env", encoding="utf-8"):
    if _l.startswith("SECAPI_IO_KEY="):
        KEY = _l.strip().split("=", 1)[1]


def post(url, payload):
    body = json.dumps(payload).encode()
    req = urllib.request.Request(url, data=body, headers={
        "Content-Type": "application/json", "User-Agent": "ThinkFree/1.0"})
    with urllib.request.urlopen(req, timeout=35) as r:
        raw = r.read()
        if raw[:2] == b"\x1f\x8b":
            raw = gzip.decompress(raw)
        return json.loads(raw)


def tickers():
    s = open(ROOT / "webapp" / "js" / "influence_data.js", encoding="utf-8").read()
    d = json.loads(s[s.index("{"): s.rindex("}") + 1])
    return list((d.get("companies") or {}).keys())


def main():
    if not KEY:
        print("ERROR: SECAPI_IO_KEY missing from .env")
        return
    tks = tickers()
    # resume: keep companies already fetched so repeated runs accumulate past rate limits
    out = {}
    if OUT.exists():
        try:
            s = OUT.read_text(encoding="utf-8")
            out = json.loads(s[s.index("{"): s.rindex("}") + 1]).get("byTicker", {})
        except Exception:
            out = {}
    todo = [t for t in tks if t not in out]
    print(f"SEC: {len(out)} already cached, fetching {len(todo)} more (of {len(tks)})...")
    hit_limit = False
    for tk in todo:
        if hit_limit:
            break
        rec = {}
        # current board / directors
        try:
            db = post("https://api.sec-api.io/directors-and-board-members?token=" + KEY,
                      {"query": f"ticker:{tk}", "from": "0", "size": "1",
                       "sort": [{"filedAt": {"order": "desc"}}]})
            data = db.get("data") or []
            if data:
                d0 = data[0]
                rec["entityName"] = d0.get("entityName")
                rec["filedAt"] = (d0.get("filedAt") or "")[:10]
                board = []
                for m in (d0.get("directors") or []):
                    board.append({
                        "name": m.get("name"),
                        "position": m.get("position") or m.get("title") or "Director",
                        "age": m.get("age"),
                        "since": m.get("directorSince") or m.get("since"),
                        "committees": m.get("committeeMemberships") or m.get("committees") or [],
                        "independent": m.get("independent"),
                    })
                rec["board"] = board
        except Exception as e:  # noqa: BLE001
            print(f"  ! {tk} directors: {str(e)[:80]}")
            if "429" in str(e):
                hit_limit = True; print("  rate limited (429) - stopping; re-run later to resume."); break
        # latest 10-K
        try:
            fq = post("https://api.sec-api.io?token=" + KEY,
                      {"query": f'ticker:{tk} AND formType:"10-K"', "from": "0", "size": "1",
                       "sort": [{"filedAt": {"order": "desc"}}]})
            fl = (fq.get("filings") or [])
            if fl:
                rec["latest_10k"] = {"filedAt": (fl[0].get("filedAt") or "")[:10],
                                     "url": fl[0].get("linkToFilingDetails") or fl[0].get("linkToHtml")}
        except Exception as e:  # noqa: BLE001
            print(f"  ! {tk} 10-K: {str(e)[:80]}")
            if "429" in str(e):
                hit_limit = True
        if rec:
            out[tk] = rec
            print(f"  + {tk}: board {len(rec.get('board', []))} | 10-K {rec.get('latest_10k', {}).get('filedAt', 'n/a')}")
        time.sleep(0.15)

    data = {"source": "sec-api.io (SEC EDGAR)", "byTicker": out, "count": len(out)}
    OUT.parent.mkdir(parents=True, exist_ok=True)
    blob = json.dumps(data, ensure_ascii=False, indent=1).replace(" — ", " - ").replace("—", " - ").replace("–", "-")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by webapp/build_sec.py (sec-api.io). No API key stored here.\n")
        f.write("window.SEC_DATA = " + blob)
        f.write(";\n")
    print(f"\nwrote {OUT} ({OUT.stat().st_size//1024} KB) - {len(out)} companies")


if __name__ == "__main__":
    main()
