"""ThinkFree - S&P 500 constituents -> InfluenceWeb sectors.

Pulls the full S&P 500 list (ticker, company, GICS sector + sub-industry) and
maps each company to one of ThinkFree's InfluenceWeb sectors so every sector can
show its real membership (top names by default, with "View More" for the rest).

Writes webapp/js/sp500_data.js (window.SP500). No API key needed.
Run:  ./tf_env/bin/python webapp/build_sp500.py
Source: github.com/datasets/s-and-p-500-companies (public domain)
"""
from __future__ import annotations

import csv
import io
import json
import urllib.request
from pathlib import Path

OUT = Path(__file__).resolve().parent / "js" / "sp500_data.js"
URL = "https://raw.githubusercontent.com/datasets/s-and-p-500-companies/main/data/constituents.csv"


def tf_sector(gics, sub):
    s = (sub or "").lower()
    if gics == "Industrials":
        if "aerospace" in s or "defense" in s:
            return "Defense"
        if any(k in s for k in ["air freight", "airline", "ground transport", "rail", "marine",
                                 "transport", "logistic", "airport", "passenger", "trucking"]):
            return "Transportation"
        return "Industrials"
    if gics == "Information Technology":
        return "Technology"
    if gics == "Health Care":
        if any(k in s for k in ["pharmaceutical", "biotechnology", "life sciences"]):
            return "Pharmaceuticals"
        return "Healthcare"
    if gics == "Financials":
        return "Financial Services"
    if gics == "Energy":
        return "Oil & Gas"
    if gics == "Utilities":
        return "Energy"
    if gics == "Communication Services":
        return "Telecommunications"
    if gics == "Real Estate":
        return "Real Estate"
    if gics in ("Consumer Discretionary", "Consumer Staples"):
        return "Consumer Goods"
    if gics == "Materials":
        return "Materials"
    return "Industrials"


def main():
    req = urllib.request.Request(URL, headers={"User-Agent": "ThinkFree/1.0"})
    with urllib.request.urlopen(req, timeout=30) as r:
        text = r.read().decode("utf-8")
    rows = list(csv.DictReader(io.StringIO(text)))
    by_ticker, counts = {}, {}
    for row in rows:
        tk = row["Symbol"].strip()
        gics = row["GICS Sector"].strip()
        sub = row["GICS Sub-Industry"].strip()
        sec = tf_sector(gics, sub)
        by_ticker[tk] = {"name": row["Security"].strip(), "sector": sec, "gics": gics, "sub": sub}
        counts[sec] = counts.get(sec, 0) + 1
    data = {"source": "S&P 500 (GICS classification)", "byTicker": by_ticker, "count": len(by_ticker)}
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by webapp/build_sp500.py. Full S&P 500 mapped to ThinkFree sectors.\n")
        f.write("window.SP500 = ")
        json.dump(data, f, ensure_ascii=False)
        f.write(";\n")
    print(f"wrote {OUT} ({OUT.stat().st_size // 1024} KB) - {len(by_ticker)} companies")
    for sec, n in sorted(counts.items(), key=lambda x: -x[1]):
        print(f"  {sec:22} {n}")


if __name__ == "__main__":
    main()
