"""ThinkFree - USASpending.gov fetcher (federal contract dollars).

For each InfluenceWeb company, pulls total federal award dollars (last ~5 yrs)
and the top awarding agencies. No API key. Writes webapp/js/usaspending_data.js.

Run:  ./tf_env/bin/python webapp/build_usaspending.py
API:  https://api.usaspending.gov/  (no auth)
"""
from __future__ import annotations

import json
import ssl
import time
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = Path(__file__).resolve().parent / "js" / "usaspending_data.js"

try:
    import certifi
    CTX = ssl.create_default_context(cafile=certifi.where())
except Exception:  # noqa: BLE001
    CTX = ssl.create_default_context()
    CTX.check_hostname = False
    CTX.verify_mode = ssl.CERT_NONE

TIME = [{"start_date": "2020-01-01", "end_date": "2025-12-31"}]
AWARD_TYPES = ["A", "B", "C", "D"]   # contracts


def post(url, payload):
    req = urllib.request.Request(url, data=json.dumps(payload).encode(),
                                 headers={"Content-Type": "application/json", "User-Agent": "ThinkFree/1.0"})
    with urllib.request.urlopen(url=req, timeout=40, context=CTX) as r:
        return json.load(r)


def fmt(n):
    if not n:
        return None
    a = abs(n)
    if a >= 1e12:
        return f"${a/1e12:.2f}T"
    if a >= 1e9:
        return f"${a/1e9:.1f}B"
    if a >= 1e6:
        return f"${a/1e6:.1f}M"
    if a >= 1e3:
        return f"${a/1e3:.0f}K"
    return f"${a:,.0f}"


def company_names():
    """ticker -> recipient name (use LittleSis legal name, fall back to ticker)."""
    s = open(ROOT / "webapp" / "js" / "influence_data.js", encoding="utf-8").read()
    d = json.loads(s[s.index("{"): s.rindex("}") + 1])
    out = {}
    for tk, c in (d.get("companies") or {}).items():
        nm = (c.get("name") or tk).replace(", Inc.", "").replace(" Inc.", "").replace(",", "")
        out[tk] = nm
    return out


def fetch(name):
    # total award amount grouped by awarding agency
    body = {
        "filters": {"award_type_codes": AWARD_TYPES, "recipient_search_text": [name], "time_period": TIME},
        "limit": 6, "page": 1,
    }
    d = post("https://api.usaspending.gov/api/v2/search/spending_by_category/awarding_agency/", body)
    results = d.get("results", [])
    total = sum(r.get("amount", 0) for r in results)
    agencies = [{"agency": r.get("name"), "amount": r.get("amount"), "amount_fmt": fmt(r.get("amount"))}
                for r in results if r.get("amount")]
    return total, agencies


def main():
    names = company_names()
    print(f"Fetching USASpending federal contracts for {len(names)} companies...")
    out = {}
    # resume support
    if OUT.exists():
        try:
            s = OUT.read_text(encoding="utf-8")
            out = json.loads(s[s.index("{"): s.rindex("}") + 1]).get("byTicker", {})
        except Exception:
            out = {}
    todo = [(t, n) for t, n in names.items() if t not in out]
    print(f"  {len(out)} cached, fetching {len(todo)} more...")
    for tk, name in todo:
        try:
            total, agencies = fetch(name)
            out[tk] = {
                "recipient": name,
                "total_contracts": total,
                "total_contracts_fmt": fmt(total),
                "top_agencies": agencies,
                "url": f"https://www.usaspending.gov/search?keyword={urllib.parse.quote(name)}",
            }
            print(f"  + {tk}: {name[:26]:28} {fmt(total) or '$0'} ({len(agencies)} agencies)")
            time.sleep(0.5)
        except Exception as e:  # noqa: BLE001
            print(f"  x {tk}: {str(e)[:70]}")
            time.sleep(0.5)

    data = {"source": "USASpending.gov (federal awards 2020-2025)", "byTicker": out, "count": len(out)}
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by webapp/build_usaspending.py (USASpending.gov)\n")
        f.write("window.USA_DATA = ")
        json.dump(data, f, ensure_ascii=False, indent=1)
        f.write(";\n")
    print(f"\nwrote {OUT} ({OUT.stat().st_size//1024} KB) - {len(out)} companies")


if __name__ == "__main__":
    main()
