"""ThinkFree - Census ACS enrichment for the Constituent layer.

Adds housing + affordability data (median home value, median rent, median
household income, poverty rate, population) from the Census ACS 1-year API to
webapp/js/states_data.js, then recomputes affordability + prosperity/pressure.

One API call pulls all states. CENSUS_API_KEY read from .env.

Run:  ./tf_env/bin/python webapp/build_census.py   (run after build_states.py)
"""
from __future__ import annotations

import json
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STATES_JS = Path(__file__).resolve().parent / "js" / "states_data.js"
YEAR = 2023

KEY = None
for _l in open(ROOT / ".env", encoding="utf-8"):
    if _l.startswith("CENSUS_API_KEY="):
        KEY = _l.strip().split("=", 1)[1]

# ACS variables
VARS = {
    "B19013_001E": "median_household_income",
    "B25077_001E": "median_home_value",
    "B25064_001E": "median_rent",
    "B17001_002E": "poverty_count",
    "B01003_001E": "population",
}
# Census numeric state FIPS -> postal
FIPS = {
    "01": "AL", "02": "AK", "04": "AZ", "05": "AR", "06": "CA", "08": "CO", "09": "CT",
    "10": "DE", "11": "DC", "12": "FL", "13": "GA", "15": "HI", "16": "ID", "17": "IL",
    "18": "IN", "19": "IA", "20": "KS", "21": "KY", "22": "LA", "23": "ME", "24": "MD",
    "25": "MA", "26": "MI", "27": "MN", "28": "MS", "29": "MO", "30": "MT", "31": "NE",
    "32": "NV", "33": "NH", "34": "NJ", "35": "NM", "36": "NY", "37": "NC", "38": "ND",
    "39": "OH", "40": "OK", "41": "OR", "42": "PA", "44": "RI", "45": "SC", "46": "SD",
    "47": "TN", "48": "TX", "49": "UT", "50": "VT", "51": "VA", "53": "WA", "54": "WV",
    "55": "WI", "56": "WY",
}


def clamp(v, lo=0, hi=100):
    return max(lo, min(hi, v))


def main():
    if not KEY:
        print("ERROR: CENSUS_API_KEY missing")
        return
    if not STATES_JS.exists():
        print("ERROR: run build_states.py first")
        return
    s = STATES_JS.read_text(encoding="utf-8")
    data = json.loads(s[s.index("{"): s.rindex("}") + 1])
    out = data["byState"]

    cols = ",".join(VARS.keys())
    url = f"https://api.census.gov/data/{YEAR}/acs/acs1?get=NAME,{cols}&for=state:*&key={KEY}"
    print(f"Fetching Census ACS {YEAR} for all states...")
    req = urllib.request.Request(url, headers={"User-Agent": "ThinkFree/1.0"})
    with urllib.request.urlopen(req, timeout=30) as r:
        rows = json.load(r)
    header = rows[0]
    idx = {h: i for i, h in enumerate(header)}
    for row in rows[1:]:
        fips = row[idx["state"]]
        st = FIPS.get(fips)
        if not st or st not in out:
            continue
        rec = out[st]
        for var, field in VARS.items():
            try:
                rec[field] = float(row[idx[var]])
            except (ValueError, KeyError, TypeError):
                pass
        # derived: poverty rate, price-to-income, affordability
        pop = rec.get("population")
        pov = rec.get("poverty_count")
        if pop and pov:
            rec["poverty_rate"] = round(pov / pop * 100, 1)
        inc = rec.get("median_household_income")
        hv = rec.get("median_home_value")
        if inc and hv:
            rec["price_to_income"] = round(hv / inc, 1)
            # affordability 0-100 (higher = more affordable); ~2x income = 100, ~9x = 0
            rec["affordability"] = round(clamp((9 - hv / inc) / 7 * 100))
        rent = rec.get("median_rent")
        if rent and inc:
            rec["rent_burden_pct"] = round(rent * 12 / inc * 100, 1)
        print(f"  + {st}: inc ${inc:,.0f} | home ${hv:,.0f} | rent ${rent:,.0f} | P/I {rec.get('price_to_income')} | afford {rec.get('affordability')}")

    # recompute prosperity/pressure with affordability included
    for st, v in out.items():
        unemp = v.get("unemployment")
        incg = v.get("income_growth") or 0
        hpg = v.get("house_price_growth") or 0
        afford = v.get("affordability")
        pov = v.get("poverty_rate")
        prosperity = 0
        if afford is not None:
            prosperity += afford * 0.30
        if unemp is not None:
            prosperity += clamp((7 - unemp) / 7 * 30, 0, 30)
        if pov is not None:
            prosperity += clamp((18 - pov) / 18 * 25, 0, 25)
        prosperity += clamp(incg * 2, -8, 15)
        v["prosperity_score"] = round(clamp(prosperity))
        pressure = 0
        if afford is not None:
            pressure += (100 - afford) * 0.45
        pressure += clamp((hpg - incg) * 4, 0, 30)
        if v.get("rent_burden_pct"):
            pressure += clamp((v["rent_burden_pct"] - 25) * 1.5, 0, 25)
        v["pressure_score"] = round(clamp(pressure))

    data["source"] = "FRED + Census ACS " + str(YEAR)
    with open(STATES_JS, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by build_states.py + build_census.py. No API key stored here.\n")
        f.write("window.STATES_DATA = ")
        json.dump(data, f, ensure_ascii=False, indent=1)
        f.write(";\n")
    print(f"\nupdated {STATES_JS} ({STATES_JS.stat().st_size//1024} KB)")


if __name__ == "__main__":
    main()
