"""ThinkFree - Finnhub live price + profile fetcher.

The ticker/company popup needs price, market cap, and industry, which are not in
any of the SEC/USASpending/Influence data files. This pulls them from Finnhub for
every ticker referenced anywhere in the app (SEC bulk, influence, USASpending,
congressional trades, bill tickers, news symbols) and writes a compact lookup.

FINNHUB_API_KEY is read from .env and never written to output or logs.
Writes webapp/js/prices_data.js  (window.PRICES_DATA).

Finnhub free tier = 60 calls/min; this sleeps to stay under that.

Run:  ./tf_env/bin/python webapp/build_prices.py
Docs: https://finnhub.io/docs/api
"""
from __future__ import annotations

import json
import re
import time
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
JS = Path(__file__).resolve().parent / "js"
OUT = JS / "prices_data.js"
BASE = "https://finnhub.io/api/v1/"
SLEEP = 1.1   # ~55 calls/min (2 calls/ticker); stays under the 60/min free cap

KEY = None
for _line in open(ROOT / ".env", encoding="utf-8"):
    if _line.startswith("FINNHUB_API_KEY="):
        KEY = _line.strip().split("=", 1)[1]


def _load_window(fname, var):
    """Parse a window.X = {...}; data file into a dict."""
    p = JS / fname
    if not p.exists():
        return {}
    txt = p.read_text(encoding="utf-8")
    i = txt.index(var) + len(var)
    return json.loads(txt[i:].rstrip().rstrip(";").strip())


def ticker_universe():
    tk = set()
    secb = _load_window("secbulk_data.js", "window.SECBULK_DATA =").get("byTicker", {})
    tk |= set(secb)
    iw = _load_window("influence_data.js", "window.IW_DATA =")
    tk |= set(iw.get("companies", iw.get("byTicker", {})))
    usa = _load_window("usaspending_data.js", "window.USA_DATA =").get("byTicker", {})
    tk |= set(usa)
    d = _load_window("data.js", "window.TF_DATA =")
    for t in d.get("recent_trades", []):
        if t.get("ticker"):
            tk.add(t["ticker"])
    for b in d.get("bills", []):
        tk |= set(b.get("tickers", []))
    for n in d.get("news", []):
        if n.get("symbol"):
            tk.add(n["symbol"])
    # only plausible equity tickers (1-5 uppercase letters), drop index labels
    return sorted(t for t in tk if re.fullmatch(r"[A-Z]{1,5}", t or ""))


def get(path, **params):
    params["token"] = KEY
    url = BASE + path + "?" + urllib.parse.urlencode(params)
    req = urllib.request.Request(url, headers={"User-Agent": "ThinkFree/1.0"})
    with urllib.request.urlopen(req, timeout=25) as r:
        return json.load(r)


def money(n):
    if not n:
        return None
    a = abs(n)
    if a >= 1e12:
        return f"${a/1e12:.2f}T"
    if a >= 1e9:
        return f"${a/1e9:.1f}B"
    if a >= 1e6:
        return f"${a/1e6:.1f}M"
    return f"${a:,.0f}"


def main():
    if not KEY:
        print("ERROR: FINNHUB_API_KEY missing from .env")
        return
    tickers = ticker_universe()
    print(f"Fetching Finnhub price + profile for {len(tickers)} tickers...")
    out = {}
    for tk in tickers:
        try:
            q = get("quote", symbol=tk)
            price = q.get("c")
            if not price:  # 0 or None => no data / not covered on free tier
                print(f"  - {tk}: no quote")
                time.sleep(SLEEP)
                continue
            time.sleep(SLEEP)
            prof = {}
            try:
                prof = get("stock/profile2", symbol=tk) or {}
            except Exception:
                pass
            mcap = prof.get("marketCapitalization")  # in millions
            mcap_abs = mcap * 1e6 if mcap else None
            out[tk] = {
                "price": round(price, 2),
                "change": round(q.get("d") or 0, 2),
                "change_pct": round(q.get("dp") or 0, 2),
                "market_cap": mcap_abs,
                "market_cap_fmt": money(mcap_abs),
                "name": prof.get("name"),
                "industry": prof.get("finnhubIndustry"),
                "exchange": prof.get("exchange"),
                "logo": prof.get("logo"),
                "weburl": prof.get("weburl"),
            }
            print(f"  + {tk:6} ${out[tk]['price']:>9} ({out[tk]['change_pct']:+}%) | {out[tk]['market_cap_fmt'] or '-':>8} | {out[tk]['industry'] or ''}")
            time.sleep(SLEEP)
        except Exception as e:  # noqa: BLE001
            print(f"  x {tk}: {e}")
            time.sleep(SLEEP)

    data = {"source": "Finnhub (finnhub.io)", "byTicker": out, "count": len(out)}
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by webapp/build_prices.py (Finnhub). No API key stored here.\n")
        f.write("window.PRICES_DATA = ")
        json.dump(data, f, ensure_ascii=False, indent=1)
        f.write(";\n")
    print(f"\nwrote {OUT} ({OUT.stat().st_size//1024} KB) - {len(out)} tickers")


if __name__ == "__main__":
    main()
